import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
mkdirSync('evidence',{recursive:true});
test('desktop shader render, no errors, single-screen composition',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await expect(page.getByRole('button',{name:/WebGL2 renderer/})).toBeVisible();
 await page.waitForTimeout(2500);await page.getByRole('button',{name:'Pause sphere motion',exact:true}).click();await page.waitForTimeout(250);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBe(true);
 await page.screenshot({path:'evidence/desktop-1648.png'});expect(errors).toEqual([]);
 const details=await page.locator('canvas').evaluate(c=>{const gl=(c as HTMLCanvasElement).getContext('webgl2');const ext=gl?.getExtension('WEBGL_debug_renderer_info');return{width:(c as HTMLCanvasElement).width,height:(c as HTMLCanvasElement).height,renderer:gl&&ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable'};});writeFileSync('evidence/renderer.json',JSON.stringify(details,null,2));
});
test('all five scopes change records without leakage',async({page})=>{await page.goto('/');for(const label of['Work','Operation','Research','Systems','Personal']){await page.getByRole('navigation').getByRole('button',{name:label,exact:true}).click();await expect(page.getByRole('navigation').getByRole('button',{name:label,exact:true})).toHaveAttribute('aria-current','page');}await page.getByRole('navigation').getByRole('button',{name:'Work',exact:true}).click();await page.getByRole('button',{name:'Search workspace',exact:true}).click();await page.getByLabel('Search records').fill('Velvet');await expect(page.getByText('No matching records.')).toBeVisible();});
test('keyboard search and provenance inspector',async({page})=>{await page.goto('/');await page.keyboard.press('Control+k');await page.getByLabel('Search records').fill('Velvet');await page.getByRole('dialog').getByRole('button',{name:/Velvet Accademy/}).click();await expect(page.getByRole('complementary',{name:'Record inspector'})).toBeVisible();await expect(page.getByText('DEMONSTRATION RECORD')).toBeVisible();await expect(page.getByText('design-01')).toBeVisible();await page.screenshot({path:'evidence/inspector.png'});await page.getByRole('button',{name:'Close record inspector'}).click();await expect(page.getByRole('complementary',{name:'Record inspector'})).toHaveCount(0);});
test('all category controls open useful filters',async({page})=>{await page.goto('/');for(const c of['people','projects','knowledge','sources','operations','resources']){await page.getByRole('button',{name:`Explore ${c}`,exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Close panel'}).click();}});
test('local review requires consent and never sends a request',async({page})=>{const writes:string[]=[];page.on('request',r=>{if(r.method()!=='GET')writes.push(r.method()+' '+r.url());});await page.goto('/');await page.getByRole('button',{name:/Console design handoff Example draft/}).click();await expect(page.getByRole('button',{name:'Mark reviewed'})).toBeDisabled();await page.getByRole('dialog').getByRole('checkbox').check();await page.screenshot({path:'evidence/review.png'});await page.getByRole('button',{name:'Mark reviewed'}).click();await expect(page.getByText('One decision needs you.')).toBeVisible();expect(writes).toEqual([]);});
test('priority state changes then resets',async({page})=>{await page.goto('/');const t=page.getByRole('checkbox',{name:/Review the console direction/});await t.click();await expect(t).toHaveAttribute('aria-checked','true');await page.getByRole('button',{name:'Controls',exact:true}).click();await page.getByRole('button',{name:'Reset demo'}).click();await expect(t).toHaveAttribute('aria-checked','false');});
test('command input routes search and rejects executable interpretation',async({page})=>{await page.goto('/');await page.getByLabel('Command or search').fill('<script>alert(1)</script>');await page.getByRole('button',{name:'Run local command'}).click();await expect(page.getByText('No matching records.')).toBeVisible();await page.keyboard.press('Escape');await page.getByLabel('Command or search').fill('/brief');await page.getByRole('button',{name:'Run local command'}).click();await expect(page.getByRole('heading',{name:'Your briefing'})).toBeVisible();});
test('voice is honestly disconnected and never requests media',async({page})=>{await page.addInitScript(()=>{(window as unknown as Window&{mediaCalls:number}).mediaCalls=0;if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{(window as unknown as Window&{mediaCalls:number}).mediaCalls++;throw new Error('Forbidden in demo');};});await page.goto('/');await page.getByRole('button',{name:'Voice connection information'}).click();await expect(page.getByText('Nothing is listening.')).toBeVisible();expect(await page.evaluate(()=>(window as unknown as Window&{mediaCalls:number}).mediaCalls)).toBe(0);});
test('quality, pause, focus and reduced motion controls',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Controls',exact:true}).click();await page.getByLabel('Graphics quality').selectOption('balanced');await page.getByRole('switch',{name:'Reduce motion',exact:true}).click();await expect(page.getByRole('switch',{name:'Reduce motion',exact:true})).toHaveAttribute('aria-checked','true');await page.getByRole('button',{name:'Close panel'}).click();await page.getByRole('button',{name:'Enter focus mode'}).click();await expect(page.locator('.console')).toHaveClass(/focus-mode/);await page.screenshot({path:'evidence/focus.png'});await page.getByRole('button',{name:'Exit focus mode'}).click();});
test('reduced-motion preference is honoured',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.getByRole('button',{name:'Controls',exact:true}).click();await expect(page.getByRole('switch',{name:'Reduce motion',exact:true})).toHaveAttribute('aria-checked','true');await expect(page.getByRole('switch',{name:'Reduce motion',exact:true})).toBeDisabled();});
test('WebGL unavailable keeps record navigation',async({page})=>{await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(this:HTMLCanvasElement,kind:string,...args:unknown[]){if(kind==='webgl2')return null;return original.apply(this,[kind,...args] as never);} as typeof original;});await page.goto('/');await expect(page.getByText('Graphics unavailable.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Explore projects'}).click();await expect(page.getByRole('dialog').getByRole('button',{name:/Velvet Accademy/})).toBeVisible();});
for(const viewport of[{width:1440,height:900},{width:1280,height:800},{width:1024,height:768},{width:390,height:844}]){test(`responsive ${viewport.width}x${viewport.height}`,async({page})=>{await page.setViewportSize(viewport);await page.goto('/');await page.waitForTimeout(700);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/viewport-${viewport.width}.png`,fullPage:true});await page.getByRole('button',{name:'Search workspace',exact:true}).click();await page.getByLabel('Search records').fill('console');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');});}
test('standalone preview renders with no network dependency',async({page})=>{const errors:string[]=[],requests:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.setContent(readFileSync('ALFRED-Console.html','utf8'));await expect(page.locator('canvas')).toBeVisible();await page.getByRole('button',{name:'Search workspace',exact:true}).click();await page.getByLabel('Search records').fill('Velvet');await expect(page.getByRole('dialog').getByRole('button',{name:/Velvet Accademy/})).toBeVisible();expect(requests).toEqual([]);expect(errors).toEqual([]);});
