import {type ConsoleSnapshot,type KnowledgeRecord,type Scope,validateSnapshot} from './model';
const record=(id:string,title:string,category:KnowledgeRecord['category'],scope:Scope,summary:string,detail:string):KnowledgeRecord=>({id,title,category,scope,summary,detail,kind:({people:'person',projects:'project',knowledge:'note',sources:'source',operations:'action',resources:'resource'} as const)[category],status:'Illustrative record',provenance:{id:`fixture:${id}`,label:'Console design fixture',revision:'design-01',basis:'fixture',excerpt:detail}});
export function createDemoSnapshot():ConsoleSnapshot{
 const records:KnowledgeRecord[]=[
 record('p-velvet','Velvet Accademy','projects','personal','Narrative workspace','An illustrative project record for the console. The project name provides context; no live development status is asserted.'),
 record('p-indigo','INDIGO','projects','personal','Play, live and watch','An illustrative project record. No repository, metrics, funds or live product telemetry are connected.'),
 record('p-loc8','Loc8','projects','personal','Offline connection','An illustrative project record for exploring cross-project navigation, not a field-readiness claim.'),
 record('p-brief','The next good decision','knowledge','personal','Make room for what matters','Review the two example drafts before deciding what comes next. This is authored sample copy, not a generated assessment of your day.'),
 record('p-design','Console visual direction','sources','personal','Black. Precise. Purposeful.','Use a true-black field, restrained graphite surfaces, clear conventional typography and sparse amber. Keep the knowledge sphere functional, not theatrical.'),
 record('p-boundary','Approval boundary','sources','personal','Your authority stays explicit','A proposed action is not an executed action. This demonstration records local review choices only and never contacts an external service.'),
 record('p-owner','Workspace owner','people','personal','Fictional identity placeholder','This demonstration label is not an authenticated identity and grants no permissions.'),
 record('p-reviewer','Creative collaborator','people','personal','Fictional collaborator','Example collaborator used only to demonstrate inspection. No contact account or personal information is loaded.'),
 record('p-handoff','Prepare a design handoff','operations','personal','A bounded next step','Capture the interface contract, screenshots and unresolved integration gates for the builder working on the ALFRED brain.'),
 record('p-runtime','Console renderer','resources','personal','Three.js · custom GLSL','The renderer shows decorative point structure plus separately identified fixture records. Decorative light paths are not evidence or model reasoning.'),
 record('w-studio','Studio workspace','projects','work','Creative work in context','Fictional workspace for checking separation between personal and work views. No client data is present.'),
 record('w-review','Production review','operations','work','Prepare, inspect, decide','Illustrative production review. No actual production booking or external action is performed.'),
 record('w-source','Production brief','sources','work','A clearly labelled fixture','A sample brief used to demonstrate source inspection within the work scope.'),
 record('w-person','Producer','people','work','Fictional team role','A fictional team role. Identity and authorisation remain a separate backend responsibility.'),
 record('w-memory','Editorial intent','knowledge','work','Clarity before decoration','Use generous spacing, intentional hierarchy and readable source text.'),
 record('o-plan','Operational review','projects','operation','Authorised work only','Synthetic operational context. There are no connected security devices or autonomous operational controls.'),
 record('o-decision','Review a proposed task','operations','operation','Approval before execution','An example task. A graphical control must never bypass exact server-side approval and verification.'),
 record('o-source','Scope policy','sources','operation','Keep boundaries visible','Personal, work and operational contexts do not share authority merely because they share an interface.'),
 record('r-graph','Evidence-backed navigation','projects','research','Graph as a view, not proof','Explore the distinction between authored links, reviewed claims and decorative rendering.'),
 record('r-source','Renderer design note','sources','research','Original implementation','Custom shaders render point illumination, depth fading, shell light and explicit selection. No model is running.'),
 record('r-memory','Graph semantics','knowledge','research','Every real link has a basis','The typed relationship list is distinct from the decorative spherical lattice. Selecting a record reveals only explicit fixture relationships.'),
 record('s-renderer','Graphics pipeline','resources','systems','WebGL2 renderer','A renderer can be paused, reduced in quality or replaced by accessible record navigation when WebGL is unavailable.'),
 record('s-model','Brain connection','resources','systems','Not connected','No model endpoint or credentials are configured. The typed UI contract is a handoff boundary, not a fabricated backend API.'),
 record('s-voice','Voice connection','resources','systems','Not connected','No audio is recorded and no microphone permission is requested in this build.')];
 return validateSnapshot({schemaVersion:1,mode:'demo',label:'Illustrative workspace',records,
 relationships:[{id:'e1',from:'p-velvet',to:'p-design',relation:'supported_by',provenanceId:'fixture:p-design',basis:'fixture'},{id:'e2',from:'p-handoff',to:'p-design',relation:'depends_on',provenanceId:'fixture:p-handoff',basis:'fixture'},{id:'e3',from:'p-brief',to:'p-boundary',relation:'links_to',provenanceId:'fixture:p-brief',basis:'fixture'},{id:'e4',from:'r-graph',to:'r-memory',relation:'links_to',provenanceId:'fixture:r-graph',basis:'fixture'}],
 priorities:[{id:'t1',scope:'personal',title:'Review the console direction',timing:'Next',done:false},{id:'t2',scope:'personal',title:'Prepare the builder handoff',timing:'Then',done:false},{id:'t3',scope:'personal',title:'Connect reviewed memory',timing:'Later',done:false},{id:'t4',scope:'work',title:'Read the sample production brief',timing:'Next',done:false},{id:'t5',scope:'research',title:'Inspect explicit graph links',timing:'Next',done:false}],
 proposals:[{id:'a1',scope:'personal',title:'Console design handoff',body:'Mark the example handoff draft as reviewed in this browser session. No message is sent, no repository is changed and no backend approval is created.',status:'pending',effect:'local_demo_only',revision:1},{id:'a2',scope:'personal',title:'Creative introduction',body:'Review this fictional introduction draft locally. This does not contact a person, access an address book or send anything.',status:'pending',effect:'local_demo_only',revision:1}]});
}
