import {Component,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {type KnowledgeRecord,type Relationship} from '../domain/model';
import {fibonacciPoint,makeLattice,makeOrbit,makePointField} from './geometry';
import * as shaders from './shaders';
interface Props{records:KnowledgeRecord[];relationships:Relationship[];selected:string|null;onSelect:(id:string)=>void;paused:boolean;reducedMotion:boolean;quality:'high'|'balanced';onStatus:(status:string)=>void;}
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function useGeometry(data:ReturnType<typeof makePointField>){return useMemo(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.setAttribute('aStrength',new THREE.BufferAttribute(data.strengths,1));g.setAttribute('aPhase',new THREE.BufferAttribute(data.phases,1));g.setAttribute('aWarmth',new THREE.BufferAttribute(data.warmth,1));return g;},[data]);}
function Field({high,moving}:{high:boolean;moving:boolean}){const{gl}=useThree(),elapsed=useRef(0);const data=useMemo(()=>makePointField(high?40000:14000),[high]),geometry=useGeometry(data);const uniforms=useMemo(()=>({uTime:{value:0},uDpr:{value:gl.getPixelRatio()}}),[gl]);useFrame((_,dt)=>{if(moving)elapsed.current+=Math.min(dt,.05);uniforms.uTime.value=elapsed.current;uniforms.uDpr.value=gl.getPixelRatio();});useEffect(()=>()=>geometry.dispose(),[geometry]);return <points geometry={geometry} frustumCulled={false}><shaderMaterial uniforms={uniforms} vertexShader={shaders.pointVertex} fragmentShader={shaders.pointFragment} transparent depthWrite={false} blending={THREE.AdditiveBlending}/></points>;}
function Lattice(){const data=useMemo(()=>makeLattice(),[]);const geometry=useMemo(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.setAttribute('aAlpha',new THREE.BufferAttribute(data.alpha,1));return g;},[data]);const smallNodes=useMemo(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(data.nodes.flat(),3));return g;},[data]);useEffect(()=>()=>{geometry.dispose();smallNodes.dispose();},[geometry,smallNodes]);return <><lineSegments geometry={geometry}><shaderMaterial vertexShader={shaders.edgeVertex} fragmentShader={shaders.edgeFragment} transparent depthWrite={false}/></lineSegments><points geometry={smallNodes}><pointsMaterial size={.007} color="#e0d9c9" transparent opacity={.40} sizeAttenuation depthWrite={false}/></points></>;}
function Orbit({radius,tilt,rotation}:{radius:number;tilt:number;rotation:[number,number,number]}){const geometry=useMemo(()=>new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(makeOrbit(radius,tilt),3)),[radius,tilt]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <lineSegments geometry={geometry} rotation={rotation}><lineBasicMaterial color="#8d7047" transparent opacity={.13} depthWrite={false}/></lineSegments>;}
function RecordNode({record,index,total,selected,onSelect}:{record:KnowledgeRecord;index:number;total:number;selected:boolean;onSelect:(id:string)=>void}){const{gl}=useThree();const position=useMemo(()=>new THREE.Vector3(...fibonacciPoint(index,total,1.023)),[index,total]);const starGeometry=useMemo(()=>new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute([0,0,0],3)),[]);const uniforms=useMemo(()=>({uScale:{value:selected?155:108},uDpr:{value:gl.getPixelRatio()},uSelected:{value:selected?1:0}}),[gl,selected]);useEffect(()=>()=>starGeometry.dispose(),[starGeometry]);return <group position={position}><points geometry={starGeometry}><shaderMaterial uniforms={uniforms} vertexShader={shaders.starVertex} fragmentShader={shaders.starFragment} transparent depthWrite={false} blending={THREE.AdditiveBlending}/></points><mesh onClick={e=>{e.stopPropagation();onSelect(record.id);}} onPointerOver={e=>{e.stopPropagation();gl.domElement.style.cursor='pointer';}} onPointerOut={()=>{gl.domElement.style.cursor='grab';}}><sphereGeometry args={[.035,12,8]}/><meshBasicMaterial transparent opacity={0} depthWrite={false}/></mesh>{selected&&<mesh><sphereGeometry args={[.018,16,12]}/><meshBasicMaterial color="#ffe8b6"/></mesh>}</group>;}
function EvidenceLinks({records,relationships,selected}:{records:KnowledgeRecord[];relationships:Relationship[];selected:string|null}){const geometry=useMemo(()=>{const positions:number[]=[],alpha:number[]=[];for(const edge of relationships){if(selected&&edge.from!==selected&&edge.to!==selected)continue;const ai=records.findIndex(r=>r.id===edge.from),bi=records.findIndex(r=>r.id===edge.to);if(ai<0||bi<0)continue;const a=new THREE.Vector3(...fibonacciPoint(ai,records.length)),b=new THREE.Vector3(...fibonacciPoint(bi,records.length));for(let i=0;i<32;i++)for(const t of[i/32,(i+1)/32]){const v=a.clone().lerp(b,t).normalize().multiplyScalar(1.025+Math.sin(t*Math.PI)*.018);positions.push(v.x,v.y,v.z);alpha.push(selected?.88:.38);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('aAlpha',new THREE.Float32BufferAttribute(alpha,1));return g;},[records,relationships,selected]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <lineSegments geometry={geometry}><shaderMaterial vertexShader={shaders.edgeVertex} fragmentShader={shaders.edgeFragment} transparent depthWrite={false}/></lineSegments>;}
function PostProcessing({high}:{high:boolean}){const{gl,scene,camera,size}=useThree();const composer=useMemo(()=>{const c=new EffectComposer(gl);c.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(1,1),high?.38:.22,.48,.94);c.addPass(bloom);c.addPass(new OutputPass());return c;},[gl,scene,camera,high]);useEffect(()=>{composer.setSize(size.width,size.height);},[composer,size]);useEffect(()=>()=>{for(const pass of composer.passes)pass.dispose();composer.dispose();},[composer]);useFrame((_,dt)=>composer.render(dt),1);return null;}
function Scene(props:Props&{moving:boolean}){const{gl,camera,invalidate}=useThree(),group=useRef<THREE.Group>(null),controls=useRef<OrbitControls|null>(null);useEffect(()=>{const c=new OrbitControls(camera,gl.domElement);c.enablePan=false;c.enableZoom=false;c.enableDamping=!props.reducedMotion;c.dampingFactor=.08;c.rotateSpeed=.35;c.minPolarAngle=.55;c.maxPolarAngle=2.6;const changed=()=>invalidate();c.addEventListener('change',changed);controls.current=c;gl.domElement.style.cursor='grab';return()=>{c.removeEventListener('change',changed);c.dispose();};},[camera,gl,invalidate,props.reducedMotion]);useFrame((_,dt)=>{if(group.current&&props.moving)group.current.rotation.y+=Math.min(dt,.05)*.021;controls.current?.update();});useEffect(()=>{props.onStatus('WebGL2 renderer');},[]);useEffect(()=>{const canvas=gl.domElement;const lost=(e:Event)=>{e.preventDefault();props.onStatus('Graphics context lost');};const restored=()=>props.onStatus('WebGL2 renderer');canvas.addEventListener('webglcontextlost',lost);canvas.addEventListener('webglcontextrestored',restored);return()=>{canvas.removeEventListener('webglcontextlost',lost);canvas.removeEventListener('webglcontextrestored',restored);};},[gl,props.onStatus]);return <><group ref={group} rotation={[.12,-.15,.10]}><mesh><sphereGeometry args={[1,80,64]}/><shaderMaterial vertexShader={shaders.shellVertex} fragmentShader={shaders.shellFragment} transparent depthWrite={false} side={THREE.FrontSide}/></mesh><EvidenceLinks records={props.records} relationships={props.relationships} selected={props.selected}/><Field high={props.quality==='high'} moving={props.moving}/><Lattice/>{props.records.map((r,i)=><RecordNode key={r.id} record={r} index={i} total={props.records.length} selected={props.selected===r.id} onSelect={props.onSelect}/>)}</group><Orbit radius={1.15} tilt={.32} rotation={[.4,.15,-.2]}/><Orbit radius={1.23} tilt={.14} rotation={[1.12,.3,.48]}/><PostProcessing high={props.quality==='high'}/></>;}
export function KnowledgeSphere(props:Props){const[hidden,setHidden]=useState(document.hidden);const[available]=useState(()=>{try{const c=document.createElement('canvas');const gl=c.getContext('webgl2');if(!gl)return false;gl.getExtension('WEBGL_lose_context')?.loseContext();return true;}catch{return false;}});useEffect(()=>{if(!available)props.onStatus('Graphics unavailable');},[available,props.onStatus]);useEffect(()=>{const f=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f);},[]);const fallback=<div className="graphics-fallback" role="status"><span className="eyebrow">Knowledge view</span><h3>Graphics unavailable.</h3><p>Your records are still accessible.<br/>Choose a category to explore.</p></div>;return <div className="sphere-canvas" role="img" aria-label="Interactive three-dimensional knowledge sphere. Drag to rotate. Use category buttons or Browse records for keyboard-accessible data."><SceneBoundary fallback={fallback}>{!available?fallback:<Canvas key={props.quality} dpr={props.quality==='high'?[1.25,1.75]:[1,1.15]} frameloop={props.paused||props.reducedMotion||hidden?'demand':'always'} fallback={fallback} camera={{position:[0,0,4.5],fov:33,near:.1,far:30}} gl={{antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:false}} onCreated={({gl})=>{gl.setClearColor(0x000000,1);gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.05;}}><Scene {...props} moving={!props.paused&&!props.reducedMotion&&!hidden}/></Canvas>}</SceneBoundary></div>;}
