import {MagnifyingGlass,CaretRight,Cube,FileText,ShareNetwork,User,Crosshair,GearSix,ArrowRight,WarningCircle,Check,DownloadSimple,SpeakerSlash,Command,ShieldCheck} from '@phosphor-icons/react';
import {CATEGORIES,categoryCopy,type Category,type KnowledgeRecord} from '../domain/model';
import {useConsole,downloadJSON} from '../state/ConsoleProvider';
import {Dialog} from './Dialog';
import {AskPanel} from './AskPanel';
import {ExecutiveRecordsPanel} from './ExecutiveRecords';
import {AccessPanel} from './AccessPanel';
import {JobsPanel} from './JobsPanel';
import {RoutinesPanel} from './RoutinesPanel';
import {useState} from 'react';
import {DeskError} from '../integration/deskClient';
const APPROVAL_ERRORS:Record<string,string>={approval_mismatch:'The proposal changed. Review the current version.',evidence_or_approval_expired:'The supporting evidence changed or the approval window closed. Nothing was approved.',invalid_state:'This proposal is no longer awaiting a decision.',not_found:'Only the person who proposed this can decide it.',forbidden:'Only the person who proposed this can decide it.',cancellation_is_not_undo:'Work that has started cannot be cancelled here.'};
function ServerReview(){
 const c=useConsole(),p=c.activeProposal!,[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const inboxNote=p.capability==='vault.inbox_note',declining=c.reviewOutcome==='declined',canAct=p.status==='pending'&&p.mine&&c.live.session?.role==='owner'&&(declining||p.evidenceCurrent);
 const decide=async()=>{setBusy(true);setError('');try{
   await c.live.client.post(`/desk/actions/${encodeURIComponent(p.id)}/${declining?'cancel':'approve'}`,declining?{}:{fingerprint:p.fingerprint});
   c.setNotice(declining?'Proposal cancelled. Nothing was created or sent.':inboxNote?'Approved. ALFRED will create the file only if it is still absent.':'Approved. ALFRED will create the local draft. Nothing is sent.');c.setModal(null);void c.live.refresh();
 }catch(e){setError(e instanceof DeskError?APPROVAL_ERRORS[e.code]??`The server refused this decision (${e.code}).`:'The decision could not be sent.');if(e instanceof DeskError&&e.kind==='signed_out')c.live.fail(e);}finally{setBusy(false);}};
 return <><div className="review-scope"><WarningCircle size={20}/><span>{declining?'Cancels this exact server proposal.':inboxNote?'Approves creating this exact file with this exact text. Nothing else in your vault is changed, and nothing is sent.':'Approves this exact text through the server ledger. ALFRED creates a local draft only; nothing is sent.'}</span></div>
  <h3 className="proposal-title">{p.title}</h3><p className="proposal-body">{p.body||'No text recorded.'}</p>
  <dl className="detail-list"><div><dt>State</dt><dd>{p.serverState}</dd></div><div><dt>Evidence</dt><dd>{p.evidenceCurrent?'Current':'Changed or expired'}</dd></div><div><dt>Expires</dt><dd>{p.expiresAt?new Date(p.expiresAt).toLocaleString('en-GB'):'Unknown'}</dd></div>{p.path&&<div><dt>Creates</dt><dd>{p.path}</dd></div>}<div><dt>Fingerprint</dt><dd className="hash">{p.fingerprint?.slice(0,16)}…</dd></div><div><dt>Effect</dt><dd>{inboxNote?'New file in your vault, only if absent; never overwrites':'Local draft only, not sent'}</dd></div></dl>
  {canAct?<><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{declining?'I want to cancel this exact proposal.':inboxNote?'I approve creating this exact file with this exact text.':'I approve this exact text and nothing else.'}</span></label>{error&&<p className="sign-in-error" role="alert">{error}</p>}<div className="button-row"><button className="primary-button" disabled={!consent||busy} onClick={decide}>{declining?'Confirm cancellation':'Approve exact text'}<Check size={16}/></button><button className="secondary-button" onClick={c.closeModal}>Close</button></div></>
  :<p className="dialog-note">{p.status!=='pending'?`This proposal is ${p.serverState}.`:!p.evidenceCurrent&&!declining?'Its supporting evidence changed, so it cannot be approved. Prepare a new proposal from current sources.':'Only the owner who proposed this can decide it.'}</p>}</>;
}
function RecordIcon({category}:{category:Category}){const Icon={projects:Cube,sources:FileText,knowledge:ShareNetwork,people:User,operations:Crosshair,resources:GearSix}[category];return <Icon size={19} weight="thin"/>;}
function RecordList({items}:{items:KnowledgeRecord[]}){const{selectRecord,setModal}=useConsole();return items.length?<div className="record-list">{items.map(r=><button key={r.id} className="record-row" onClick={()=>{selectRecord(r.id);setModal(null);}}><span className="record-symbol"><RecordIcon category={r.category}/></span><span><strong>{r.title}</strong><small>{r.summary}</small></span><CaretRight size={16}/></button>)}</div>:<div className="empty-state"><ShareNetwork size={28}/><h3>No matching records.</h3><p>Try a shorter search or choose another workspace.</p></div>;}
export function ConsoleDialogs(){
 const c=useConsole();const{connected,live,modal,state,dispatch,setModal,query,setQuery,searchRef,results,shownRecords,records,priorities,pending,activeProposal,reviewConsent,setReviewConsent,reviewOutcome,setNotice,reduced,systemReduced,renderer,proposals,inputRef}=c;
 if(!modal)return null;
 const titles={ask:'Ask ALFRED',brief:'Your briefing',search:'Search your workspace',review:connected?(reviewOutcome==='declined'?'Cancel this proposal':'Review the exact proposal'):reviewOutcome==='declined'?'Decline this example':'Review the exact proposal',settings:'Console controls',voice:'Voice connection',handoff:'Builder handoff',tasks:'Your next steps',records:state.category?`${state.category[0].toUpperCase()}${state.category.slice(1)}`:'Knowledge records',security:'Authority and connections',jobs:'Bounded jobs',routines:'Routines'};
 const recordReview=(outcome:'reviewed'|'declined')=>{if(!activeProposal)return;dispatch({type:'review',id:activeProposal.id,revision:activeProposal.revision,outcome,at:new Date().toISOString()});setNotice(`Example ${outcome}. Nothing sent or executed.`);setModal(null);};
 return <Dialog title={titles[modal]} subtitle={`${state.scope.toUpperCase()} / ${modal==='review'?(connected?'SERVER APPROVAL':'LOCAL DEMONSTRATION'):modal==='ask'?'PERMITTED SOURCES':'ALFRED'}`} onClose={c.closeModal} wide={modal==='handoff'||modal==='routines'}>
 {modal==='ask'&&<AskPanel/>}
 {modal==='jobs'&&<JobsPanel/>}
 {modal==='routines'&&<RoutinesPanel/>}
 {modal==='search'&&<><div className="search-box"><MagnifyingGlass size={20}/><input ref={searchRef} aria-label="Search records" placeholder="Search titles, context and categories" value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/><kbd>ESC</kbd></div><p className="dialog-note">{connected?'Searches permitted records in this workspace. No model answer is fabricated.':`Searches the ${state.scope} fixtures only. No model answer is fabricated.`}</p><RecordList items={results}/><p className="result-count">{results.length} matching records</p></>}
 {modal==='records'&&<><p className="dialog-note">{state.category?categoryCopy[state.category].description:'Records and their source-backed links are distinct from the decorative field.'}</p><div className="filter-chips"><button className={!state.category?'active':''} onClick={()=>dispatch({type:'category',category:null})}>All</button>{CATEGORIES.map(category=><button className={state.category===category?'active':''} onClick={()=>dispatch({type:'category',category})} key={category}>{category}</button>)}</div><RecordList items={shownRecords}/></>}
 {modal==='brief'&&<><p className="dialog-note">{connected?`Counted from permitted records confirmed at ${state.snapshot.observedAt?new Date(state.snapshot.observedAt).toLocaleTimeString('en-GB'):'an unknown time'}. A count, not an assessment.`:'An overview calculated from this local demonstration, not a live assessment of your projects.'}</p><div className="brief-metrics"><span><b>{pending.length}</b>Awaiting review</span><span><b>{priorities.filter(t=>!t.done).length}</b>Open priorities</span><span><b>{records.length}</b>Visible records</span></div><RecordList items={records.slice(0,3)}/><button className="primary-button" onClick={()=>setModal('tasks')}>Review next steps<ArrowRight size={16}/></button></>}
 {modal==='tasks'&&connected&&<ExecutiveRecordsPanel/>}
 {modal==='tasks'&&!connected&&<><p className="dialog-note">Sample priorities. Changes last for this browser session only.</p>{priorities.length?priorities.map(p=><button role="checkbox" aria-checked={p.done} key={p.id} className={`task-row ${p.done?'done':''}`} onClick={()=>dispatch({type:'priority',id:p.id})}><span className="check-ring">{p.done&&<Check size={13}/>}</span><span>{p.title}</span><small>{p.timing}</small></button>):<p className="quiet-empty">No sample priorities in this workspace.</p>}</>}
 {modal==='review'&&activeProposal&&connected&&<ServerReview/>}
 {modal==='review'&&activeProposal&&!connected&&<><div className="review-scope"><WarningCircle size={20}/><span>Local review demonstration. Nothing is sent or executed.</span></div><h3 className="proposal-title">{activeProposal.title}</h3><p className="proposal-body">{activeProposal.body}</p><dl className="detail-list"><div><dt>Revision</dt><dd>{activeProposal.revision}</dd></div><div><dt>Workspace</dt><dd>{activeProposal.scope}</dd></div><div><dt>Effect</dt><dd>Browser session only</dd></div></dl>{activeProposal.status==='pending'?<><label className="consent"><input type="checkbox" checked={reviewConsent} onChange={e=>setReviewConsent(e.target.checked)}/><span>I have read this exact example. This is not a live approval.</span></label><div className="button-row"><button className="primary-button" disabled={!reviewConsent} onClick={()=>recordReview(reviewOutcome)}>{reviewOutcome==='declined'?'Confirm decline':'Mark reviewed'}<Check size={16}/></button><button className="secondary-button" onClick={c.closeModal}>Cancel</button></div></>:<p className="dialog-note">This example is already {activeProposal.status}.</p>}</>}
 {modal==='settings'&&<><div className="settings-row"><span><strong>Graphics quality</strong><small>Changes resolution and detail without restarting the renderer.</small></span><select aria-label="Graphics quality" value={state.quality} onChange={e=>dispatch({type:'quality',quality:e.target.value as 'high'|'balanced'})}><option value="high">High</option><option value="balanced">Balanced</option></select></div><div className="settings-row"><span><strong>Reduce motion</strong><small>{systemReduced?'Your operating system requests reduced motion.':'Still rendering, with all controls available.'}</small></span><button className={`toggle ${reduced?'on':''}`} role="switch" aria-checked={reduced} aria-label="Reduce motion" disabled={Boolean(systemReduced)} onClick={()=>dispatch({type:'motion',value:!state.reducedMotion})}><i/></button></div><div className="settings-row"><span><strong>Pause sphere</strong><small>Stops rotation. Brightness never pulses.</small></span><button className={`toggle ${state.paused?'on':''}`} role="switch" aria-checked={state.paused} aria-label="Pause sphere" onClick={()=>dispatch({type:'pause'})}><i/></button></div><div className="connection-list"><h3>Actual connections</h3><div><span>Renderer</span><b>{renderer}</b></div><div><span>Workspace data</span><b>{connected?(live.connection.kind==='ready'?`ALFRED server · ${state.scope}`:live.connection.kind.replace('_',' ')):'Fictional fixtures'}</b></div><div><span>Brain / model</span><b>{connected?(state.snapshot.model?.configured?`${state.snapshot.model.name} · ${state.snapshot.model.allowed?'available on request':'not permitted for this key'}`:'No model configured · source mode'):'Not connected'}</b></div><div><span>Microphone</span><b>Off · never requested</b></div><div><span>External accounts</span><b>Not connected</b></div><div><span>Graph</span><b>{records.length} records · {c.relationships.length} explicit links</b></div></div>{connected?<><div className="button-row"><button className="secondary-button" onClick={()=>void live.refresh()}>Refresh now</button><button className="secondary-button" onClick={()=>setModal('jobs')}>Open jobs</button><button className="secondary-button" onClick={()=>setModal('routines')}>Open routines</button><button className="text-button" onClick={()=>{setModal(null);void live.signOut();}}>Sign out</button></div><p className="dialog-note">No records or credentials are saved to browser storage. The session cookie is not readable by this page. Records refresh every few seconds while this tab is visible.</p></>
 :<><div className="button-row"><button className="secondary-button" onClick={()=>downloadJSON({mode:'demo',scope:state.scope,receipts:state.receipts.filter(r=>proposals.some(p=>p.id===r.proposalId))},'ALFRED-demo-receipts.json')}><DownloadSimple size={17}/>Export review receipts</button><button className="text-button" onClick={c.resetDemo}>Reset demo</button></div><p className="dialog-note">No records or credentials are saved to browser storage. Refresh resets the demonstration. The live brain is a separate integration step.</p></>}</>}
 {modal==='voice'&&<div className="voice-empty"><SpeakerSlash size={46} weight="thin"/><h3>Nothing is listening.</h3><p>No microphone permission is requested. A later voice adapter must share the same context and authority checks, with an explicit recording state and stop control.</p><button className="primary-button" onClick={()=>{setModal(null);setTimeout(()=>inputRef.current?.focus(),50);}}>Use the keyboard<Command size={17}/></button></div>}
 {modal==='security'&&connected&&<AccessPanel/>}
 {modal==='security'&&<><div className="review-scope"><ShieldCheck size={23}/><span>{connected?'Connected to your local ALFRED server. It decides what this page may read.':'This is a disconnected design build, not an authenticated private-data environment.'}</span></div><div className="connection-list"><h3>Preserved boundaries</h3><div><span>Data</span><b>{connected?'Permitted records for this access key':'Synthetic fixtures only'}</b></div><div><span>Review effect</span><b>{connected?'Server ledger · local drafts only':'This browser session only'}</b></div><div><span>External requests</span><b>{connected?'Same-origin loopback only':'None from the offline preview'}</b></div><div><span>Microphone / camera</span><b>Never requested</b></div></div><p className="dialog-note">In the connected product, the server grants scope, validates source revisions, checks the exact approved action and records its outcome. A graph edge, a model answer or a local UI state cannot grant authority.</p><button className="secondary-button" onClick={()=>setModal('handoff')}>Read integration handoff<ArrowRight size={16}/></button></>}
 {modal==='handoff'&&<><p className="dialog-note">The existing console has been evolved, not replaced with a new stack. The Python brain and original web application are unchanged by this interface build.</p><div className="handoff-grid"><div><span className="eyebrow">PRESENTATION</span><h3>React + TypeScript</h3><p>Independent rail, header, knowledge stage, executive sections, command bar, inspector and dialogs. DOM text stays accessible.</p></div><div><span className="eyebrow">GRAPHICS</span><h3>Three.js + custom GLSL</h3><p>Stable frame ownership, fixed exposure, deterministic geometry, ordered layers and non-pulsing materials. Quality changes preserve the canvas.</p></div><div><span className="eyebrow">MEMORY</span><h3>Sources remain authoritative</h3><p>Connect note references and reviewed claims separately, preserving evidence, revision, review state, conflicts and invalidation.</p></div><div><span className="eyebrow">EXECUTION</span><h3>Approval stays server-side</h3><p>Map server proposals and result receipts, never local fixture review state. Permission checks apply before projection and after revocation.</p></div></div><p className="dialog-note">Read docs/COMPONENT_ARCHITECTURE.md, docs/BUILD_BRIEF.md and docs/NEXT_BUILDER.md in this console package. The interface adapter contract is not an invented HTTP endpoint.</p></>}
 </Dialog>;
}
