import {SurfaceTrace} from './SurfaceMotion';
import {CaretRight,Check,FileText,Cube,ShareNetwork,DotsThree,ArrowUpRight} from '@phosphor-icons/react';
import {useConsole} from '../state/ConsoleProvider';
import {milestoneProgress} from '../domain/projection';
import {useExecutiveActions} from './ExecutiveRecords';
import {AttentionSection,DerivedInsightRow} from './ExecutiveWorkflows';
import {RoutineNominationsSection} from './RoutinesPanel';
function SectionHeading({title,count,action,onAction}:{title:string;count:number;action?:string;onAction?:()=>void}){return <header className="executive-section-heading"><h3>{title}</h3>{action?<button onClick={onAction}>{action}<CaretRight size={12}/></button>:<span>{count}</span>}</header>;}
export function PrioritySection(){const{priorities,dispatch,setModal,connected,state,live}=useConsole(),actions=useExecutiveActions();
  if(connected){const open=priorities.filter(p=>!p.done),recommended=state.snapshot.recommendations??[],owner=live.session?.role==='owner';
    return <section className="executive-section"><SectionHeading title="Top priorities" count={open.length} action={priorities.length>3||recommended.length?'View all':undefined} onAction={()=>setModal('tasks')}/>
      {priorities.length?priorities.slice(0,3).map((p,i)=><button role="checkbox" aria-checked={p.done} key={p.id} disabled={!owner} className={`priority-row ${p.done?'done':''}`} onClick={()=>void actions.toggle({id:p.id,version:p.version??1,kind:'priority',done:p.done})}><span className={`priority-number ${i===0?'first':''}`}>{p.done?<Check size={12}/>:i+1}</span><span>{p.title}</span><small className={p.overdue?'overdue':''}>{p.timing}{p.responsible?` · ${p.responsible}`:''}</small></button>)
        :<p className="quiet-empty">No priorities are recorded in ALFRED yet.</p>}
      {recommended.slice(0,2).map(r=><div className="recommendation-row" key={r.fromRecord}><span><strong>{r.title}</strong><small>Recommendation · {r.reason}</small></span>{owner&&<button className="review-button" aria-label={`Accept ${r.title} as a priority`} onClick={()=>void actions.accept(r.fromRecord,r.fromVersion)}>Accept</button>}</div>)}
    </section>;}
  return <section className="executive-section"><SectionHeading title="Top priorities" count={priorities.filter(p=>!p.done).length} action={priorities.length>3?'View all':undefined} onAction={()=>setModal('tasks')}/>{priorities.length?priorities.slice(0,3).map((p,i)=><button role="checkbox" aria-checked={p.done} key={p.id} className={`priority-row ${p.done?'done':''}`} onClick={()=>dispatch({type:'priority',id:p.id})}><span className={`priority-number ${i===0?'first':''}`}>{p.done?<Check size={12}/>:i+1}</span><span>{p.title}</span><small>{p.timing}</small></button>):<p className="quiet-empty">No sample priorities in this workspace.</p>}</section>;}
export function ApprovalSection(){const{pending,openReview,connected}=useConsole();return <section className="executive-section"><SectionHeading title="Approvals" count={pending.length}/>{pending.length?pending.map(p=><div className="approval-row" key={p.id}><span className="record-symbol"><FileText size={20} weight="thin"/></span><button className="approval-title" onClick={()=>openReview(p.id)}><strong>{p.title}</strong><small>{connected?(p.evidenceCurrent?(p.capability==='vault.inbox_note'?'Awaiting your approval · create only':'Awaiting your approval · not sent'):'Conditions changed · cannot be approved'):'Local example · not sent'}</small></button><div className="approval-actions"><button className="review-button" aria-label={`Review ${p.title}`} onClick={()=>openReview(p.id)}>Review</button><button className="decline-button" aria-label={`Decline ${p.title}`} onClick={()=>openReview(p.id,'declined')}>Decline</button></div></div>):<p className="quiet-empty">Nothing waiting for review.</p>}</section>;}
export function ProjectsSection(){const{projects:all,selectRecord,openCategory,connected,state}=useConsole(),milestones=state.snapshot.milestones;
  // Connected: projects with recorded milestones first, then the rest, in their original order.
  const projects=connected?[...all].sort((a,b)=>Number(Boolean(milestones?.[b.id]))-Number(Boolean(milestones?.[a.id]))):all;return <section className="executive-section"><SectionHeading title="Active projects" count={projects.length} action={projects.length>3?'View all':undefined} onAction={()=>openCategory('projects')}/>{projects.length?projects.slice(0,3).map((r,i)=>{
  if(connected){const m=milestones?.[r.id];return <button className="project-row" key={r.id} onClick={()=>selectRecord(r.id)}><span className={`project-symbol project-symbol-${i}`}><Cube size={16} weight="thin"/></span><span className="project-content"><span className="project-title">{r.title}<small>{m?`${m.done}/${m.total} milestones`:r.origin==='reviewed_entity'?'Reviewed':'Authored'}</small></span>{m?<span className="progress-track" role="progressbar" aria-label={`${r.title} recorded milestones`} aria-valuemin={0} aria-valuemax={m.total} aria-valuenow={m.done} title="Counted from your recorded milestones only"><i style={{width:`${m.total?m.done/m.total*100:0}%`}}/></span>:<span className="project-note">No milestones recorded</span>}</span></button>;}
  const progress=milestoneProgress(r.id);return <button className="project-row" key={r.id} onClick={()=>selectRecord(r.id)}><span className={`project-symbol project-symbol-${i}`}><Cube size={16} weight="thin"/></span><span className="project-content"><span className="project-title">{r.title}<small>{progress.completed}/{progress.total} steps</small></span><span className="progress-track" role="progressbar" aria-label={`${r.title} sample milestones`} aria-valuemin={0} aria-valuemax={progress.total||1} aria-valuenow={progress.completed} title="Illustrative milestones, not live project progress"><i style={{width:`${progress.total?progress.completed/progress.total*100:0}%`}}/></span></span></button>;}):<p className="quiet-empty">{connected?'No project records in this workspace.':'No sample projects in this workspace.'}</p>}</section>;}
export function InsightSection(){const{records,selectRecord,connected,state}=useConsole();
  if(connected){const insight=state.snapshot.insights?.[0],derived=state.snapshot.derivedInsights?.length?1:0;return <section className="executive-section insight-section"><SectionHeading title="Recent insight" count={(insight?1:0)+derived}/>{insight?<button className="insight-row" onClick={()=>selectRecord(insight.recordId)}><span className="record-symbol"><ShareNetwork size={22} weight="thin"/></span><span><strong>{insight.title}</strong><small>{insight.summary}</small><em>Your reviewed statement · view support</em></span><ArrowUpRight size={15}/></button>:<p className="quiet-empty">No reviewed statement yet. Insights appear only from accepted, current reviews.</p>}<DerivedInsightRow/></section>;}
  const source=records.find(r=>r.category==='knowledge')??records.find(r=>r.category==='sources');return <section className="executive-section insight-section"><SectionHeading title="Recent insight" count={source?1:0}/>{source?<button className="insight-row" onClick={()=>selectRecord(source.id)}><span className="record-symbol"><ShareNetwork size={22} weight="thin"/></span><span><strong>{source.title}</strong><small>{source.summary}</small><em>View source</em></span><ArrowUpRight size={15}/></button>:<p className="quiet-empty">No source-backed sample insight.</p>}</section>;}
export function ExecutivePanel(){const{setModal}=useConsole();return <aside className="executive-panel" aria-label="Executive brief"><SurfaceTrace/><header className="executive-heading"><h2>Executive brief</h2><button className="icon-button" aria-label="Open executive briefing" onClick={()=>setModal('brief')}><DotsThree size={20}/></button></header><div className="executive-body"><PrioritySection/><AttentionSection/><RoutineNominationsSection/><ApprovalSection/><ProjectsSection/><InsightSection/></div><footer className="executive-footer"><button onClick={()=>setModal('security')}>Data and permissions<CaretRight size={11}/></button></footer></aside>;}
