import {useEffect,useRef} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import {X,LinkSimple,CaretRight,DownloadSimple} from '@phosphor-icons/react';
import {useConsole,downloadJSON} from '../state/ConsoleProvider';
function InspectorBody(){
  const{selected,relationships,records,dispatch,selectRecord}=useConsole(),heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;heading.current?.focus();return()=>{if(previous?.isConnected)previous.focus();};},[]);
  if(!selected)return null;
  const edges=relationships.filter(e=>e.from===selected.id||e.to===selected.id);
  return <><header className="inspector-header"><span className="eyebrow">{selected.category} / inspect</span><button className="icon-button" aria-label="Close record inspector" onClick={()=>dispatch({type:'select',id:null})}><X size={20}/></button></header><div className="inspector-body"><span className="demo-badge">DEMONSTRATION RECORD</span><h2 ref={heading} tabIndex={-1}>{selected.title}</h2><p className="inspector-summary">{selected.summary}</p><section className="inspector-section"><h3>Context</h3><p>{selected.detail}</p></section><section className="inspector-section"><h3>Provenance</h3><dl className="detail-list"><div><dt>Source</dt><dd>{selected.provenance.label}</dd></div><div><dt>Revision</dt><dd>{selected.provenance.revision}</dd></div><div><dt>Basis</dt><dd>{selected.provenance.basis}</dd></div><div><dt>Workspace</dt><dd>{selected.scope}</dd></div></dl><blockquote>{selected.provenance.excerpt}</blockquote></section><section className="inspector-section"><h3>Explicit relationships</h3>{edges.length?edges.map(e=>{const other=records.find(r=>r.id===(e.from===selected.id?e.to:e.from));return <button className="linked-record" key={e.id} onClick={()=>other&&selectRecord(other.id)}><LinkSimple size={17}/><span><small>{e.relation.replaceAll('_',' ')}</small>{other?.title}</span><CaretRight size={14}/></button>;}):<p>No explicit links in this fixture. Background particles are decorative, not relationships.</p>}</section><button className="secondary-button export-button" onClick={()=>downloadJSON({mode:'demo',record:selected,relationships:edges},`ALFRED-${selected.id}-demo.json`)}><DownloadSimple size={17}/>Export record</button></div></>;
}
export function RecordInspector(){const{selected}=useConsole();return <AnimatePresence>{selected&&<motion.aside key="inspector" className="inspector" initial={{opacity:0,x:16}} animate={{opacity:1,x:0}} exit={{opacity:0,x:16}} transition={{duration:.18}} aria-label="Record inspector"><InspectorBody/></motion.aside>}</AnimatePresence>;}
