"""Browser-to-backend acceptance for the connected premium console.

Runs the real loopback ALFRED server over a synthetic vault, serves the built
console from the same origin and drives it in Chromium. Testing-only tooling;
requires `npm run build` in console/ first. No model, account or private data.
"""
import json
import os
import re
from pathlib import Path
import sys
import tempfile
import threading
import time
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from alfred.desk import init_demo, start_local_jobs
from alfred.knowledge import KnowledgeStore, KnowledgeSupervisor, MarkdownVault
from alfred.desk_http import DeskHTTPServer
from alfred.reviewed_memory import ReviewedMemory
from alfred.policy import IdentityPolicy
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / 'console' / 'dist'
out = Path(os.environ.get('ALFRED_CONSOLE_OUTPUT', ROOT / 'docs' / 'evidence' / 'console-connected'))
out.mkdir(parents=True, exist_ok=True)
checks, console_messages, page_errors, foreign, job_requests = [], [], [], [], []


def check(name, condition=True):
    assert condition, name
    checks.append(name)


def note(store, bearer, title):
    return next(n for n in store.knowledge(bearer)['nodes'] if n['title'] == title)


if not (DIST / 'index.html').is_file():
    raise SystemExit('Build the console first: cd console && npm run build')

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp); home = root / 'demo'; keys = init_demo(home)
    store = KnowledgeStore(home / 'desk.sqlite')
    sup = KnowledgeSupervisor(store, keys['owner'], keys['source'], home / 'project', vault=home / 'vault', interval=.2)
    sup.cycle(); sup.start()
    jobs, halt_jobs = start_local_jobs(store, keys['owner'], home)
    # A second workspace that must never appear.
    other_source = store.provision('other-workspace', 'other-source', 'source')
    other = root / 'other-vault'; other.mkdir()
    (other / 'Hidden.md').write_text('# Zephyrmarker\nAnother workspace.\n')
    MarkdownVault(store, other_source, other).scan()
    server = DeskHTTPServer(store, sup, port=0, console_dist=DIST, jobs=jobs)
    thread = threading.Thread(target=server.serve_forever, kwargs={'poll_interval': .01}, daemon=True); thread.start()
    memory = ReviewedMemory(store)
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH', '/usr/bin/chromium'), headless=True,
                                        args=['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'])
            context = browser.new_context(viewport={'width': 1648, 'height': 928}, device_scale_factor=1)
            page = context.new_page()
            page.on('console', lambda m: console_messages.append(f'{m.type}: {m.text}'))
            page.on('pageerror', lambda e: page_errors.append(str(e)))
            page.on('request', lambda r: foreign.append(r.url) if not r.url.startswith(server.origin) else None)
            page.on('request', lambda r: job_requests.append(r.url) if '/desk/jobs' in r.url else None)
            page.goto(server.origin + '/console')
            check('console is served by the ALFRED origin', page.url == server.origin + '/console/')
            expect(page.get_by_role('heading', name='Sign in to ALFRED')).to_be_visible()
            body = page.locator('body').inner_text()
            check('signed-out view shows no fixture records', 'Velvet Accademy' not in body and 'Demo workspace' not in body)
            check('signed-out graph has zero records', '0 records' in page.locator('.graph-view-label').inner_text())
            page.get_by_label('Access key').fill('x' * 43); page.get_by_role('button', name='Sign in').click()
            expect(page.get_by_role('alert')).to_contain_text('not accepted')
            check('wrong key is refused without revealing data')
            page.get_by_label('Access key').fill(keys['owner']); page.get_by_role('button', name='Sign in').click()
            expect(page.locator('.connection-state')).to_have_text('Connected')
            check('owner signs in through the real session endpoint')
            expect(page.locator('.graph-view-label')).to_contain_text('21 records')
            label = page.locator('.graph-view-label').inner_text()
            links = len(store.knowledge(keys['owner'])['links'])
            check('graph counts come from permitted backend records', f'21 records · {links} links' in label)
            check('workspace selector lists only the server workspace', page.locator('#scope-select option').all_inner_texts() == ['Demo production'])
            check('command bar states connected source mode', 'CONNECTED · SOURCE MODE' in page.locator('.command-meta').inner_text())
            check('no fixture or other-workspace names after sign-in', all(x not in page.locator('body').inner_text() for x in ('Velvet Accademy', 'Zephyrmarker', 'INDIGO')))
            page.wait_for_timeout(800)
            page.screenshot(path=str(out / 'connected-desktop.png'))
            page.get_by_role('button', name='Explore projects').click()
            dialog = page.get_by_role('dialog')
            for title in ('Sample film', 'ALFRED', 'Home node concept'):
                expect(dialog.get_by_role('button', name=title)).to_be_visible()
            check('project callout lists actual project notes')
            dialog.get_by_role('button', name='Sample film').click()
            inspector = page.get_by_role('complementary', name='Record inspector')
            expect(inspector).to_contain_text('AUTHORED NOTE · NOT A VERIFIED FACT')
            expect(inspector).to_contain_text('projects/Sample Film.md')
            expect(inspector.locator('.source-lines')).to_contain_text('The fictional production brings its brief')
            check('selecting a project shows its exact source path and lines')
            expect(inspector).to_contain_text('authored link')
            inspector.get_by_role('button', name='Sample producer').first.click()
            expect(inspector.get_by_role('heading', name='Sample producer')).to_be_visible()
            check('following a supported relationship opens the neighbour record')
            page.screenshot(path=str(out / 'connected-inspector.png'))
            # Reviewed memory created through the real service appears after refresh.
            producer = note(store, keys['owner'], 'Sample producer')
            memory.create_entity(keys['owner'], {'id': 'film', 'kind': 'project', 'name': 'Sample film'})
            memory.create_entity(keys['owner'], {'id': 'producer', 'kind': 'person', 'name': 'Sample producer'})
            claim = memory.propose(keys['owner'], {'request_id': 'r1', 'subject_id': 'film', 'predicate': 'responsible_person', 'object_id': 'producer', 'value': None,
                                                   'valid_from': None, 'valid_until': None,
                                                   'evidence': {'note_id': producer['id'], 'sha256': producer['sha256'], 'revision': producer['revision'], 'start_line': 8, 'end_line': 8}})
            memory.review(keys['owner'], claim['id'], {'version': 1, 'decision': 'accept', 'replaces_id': None, 'replaces_version': None})
            page.get_by_label('Close record inspector').click()
            expect(page.locator('.insight-section')).to_contain_text('responsible person: Sample producer', timeout=15000)
            check('accepted reviewed statement appears as an insight after refresh')
            expect(page.locator('.graph-view-label')).to_contain_text('23 records')
            page.locator('.insight-row').click()
            expect(inspector).to_contain_text('REVIEWED MEMORY · YOUR JUDGEMENT')
            expect(inspector).to_contain_text('Accepted and current')
            expect(inspector.locator('blockquote')).to_contain_text('Fictional responsibility')
            check('reviewed entity shows review basis and exact original support')
            expect(inspector).to_contain_text('reviewed relationship · responsible person')
            check('reviewed relationship is labelled separately from authored links')
            page.screenshot(path=str(out / 'connected-reviewed.png'))
            # Changing the supporting source makes the review visibly unusable.
            path = home / 'vault' / 'people' / 'Sample Producer.md'
            path.write_text(path.read_text().replace('Fictional responsibility', 'Changed responsibility'))
            expect(inspector).to_contain_text('Source changed · review needed', timeout=15000)
            expect(page.locator('.insight-section')).to_contain_text('No reviewed statement yet', timeout=15000)
            check('source change invalidates the displayed review and insight')
            check('stale quote is no longer displayed', 'Fictional responsibility' not in inspector.inner_text())
            # M05: forgetting through the console, with a server receipt.
            film_note = note(store, keys['owner'], 'Sample film')
            status = memory.propose(keys['owner'], {'request_id': 'r2', 'subject_id': 'film', 'predicate': 'status', 'object_id': None, 'value': 'in pre-production',
                                                    'valid_from': None, 'valid_until': None,
                                                    'evidence': {'note_id': film_note['id'], 'sha256': film_note['sha256'], 'revision': film_note['revision'], 'start_line': 8, 'end_line': 8}})
            memory.review(keys['owner'], status['id'], {'version': 1, 'decision': 'accept', 'replaces_id': None, 'replaces_version': None})
            statement = inspector.locator('.statement').filter(has_text='in pre-production')
            expect(statement).to_be_visible(timeout=15000)
            statement.get_by_role('button', name='Forget this statement').click()
            inspector.get_by_role('button', name='Confirm forget').click()
            expect(page.get_by_role('status').filter(has_text='Not secure erasure')).to_be_visible()
            expect(inspector).to_contain_text('Forgotten · value removed', timeout=15000)
            check('forgetting removes the value from the open inspector', 'in pre-production' not in inspector.inner_text())
            check('forgetting is recorded with a receipt', memory.view(keys['owner'])['claims'][0]['state'] == 'forgotten')
            page.get_by_label('Close record inspector').click()
            # Stage B: the selected project is context for the next question.
            command = page.get_by_label('Command or search')
            command.fill('What still needs confirming?'); command.press('Enter')
            ask = page.get_by_role('dialog')
            expect(ask).to_contain_text('No record selected')
            expect(ask.locator('.evidence').first).to_be_visible(timeout=15000)
            unfocused = ask.locator('.evidence header .text-button').all_inner_texts()
            check('unfocused question uses the whole permitted workspace', 'Sample film' not in unfocused[:1])
            check('missing model is reported explicitly', 'no model configured' in ask.inner_text())
            support = ask.get_by_role('region', name='What supports this answer')
            expect(support).to_be_visible(timeout=15000)
            check('each answer states what supports it, as counts and word coverage, never truth',
                  'excerpt' in support.inner_text() and 'No model used' in support.inner_text() and 'not an answer' in support.inner_text())
            page.keyboard.press('Escape')
            command.fill('What is the sample film budget?'); command.press('Enter')
            expect(page.get_by_role('dialog').get_by_role('region', name='What supports this answer')).to_contain_text('Not found in what is shown: “budget”', timeout=15000)
            check('words the sources do not contain are named, not glossed over')
            page.screenshot(path=str(out / 'connected-answer-support.png'))
            page.keyboard.press('Escape')
            page.get_by_role('button', name='Explore projects').click()
            films = page.get_by_role('dialog').locator('.record-row').filter(has_text='Sample film')
            check('authored note and reviewed entity with the same name stay separate', films.count() == 2)
            films.filter(has_text='The fictional production').click()
            command.fill('What still needs confirming?'); command.press('Enter')
            expect(ask).to_contain_text('Context: Sample film')
            expect(ask.locator('.evidence').first).to_contain_text('Selected record', timeout=15000)
            check('selecting a project changes the next question', ask.locator('.evidence header .text-button').first.inner_text().strip() == 'Sample film')
            check('answer exposes source path, lines and basis', 'projects/Sample Film.md' in ask.inner_text() and 'not a generated answer' in ask.inner_text())
            page.screenshot(path=str(out / 'connected-ask.png'))
            ask.locator('summary').click()
            ask.get_by_label('Draft text').fill('Synthetic follow-up for the sample film.')
            ask.get_by_role('button', name='Propose draft').click()
            expect(page.get_by_role('status').filter(has_text='Draft proposed')).to_be_visible()
            check('proposing a draft from an answer is a separate explicit step')
            # The open answer is withdrawn when its source changes.
            film = home / 'vault' / 'projects' / 'Sample Film.md'
            film.write_text(film.read_text().replace('brings its brief', 'now brings its brief'))
            expect(ask).to_contain_text('It was withdrawn rather than shown stale', timeout=20000)
            check('changed source withdraws the displayed answer')
            page.keyboard.press('Escape')
            if page.get_by_label('Close record inspector').count():
                page.get_by_label('Close record inspector').click()
            row = page.locator('.approval-row').filter(has_text='Local message draft')
            expect(row.first).to_be_visible(timeout=15000)
            row.first.get_by_role('button', name='Review Local message draft').click()
            expect(page.get_by_role('dialog')).to_contain_text('cannot be approved')
            check('draft bound to changed evidence cannot be approved')
            page.get_by_role('dialog').get_by_label('Close panel').click()
            row.first.get_by_role('button', name='Decline Local message draft').click()
            dialog = page.get_by_role('dialog')
            dialog.get_by_text('I want to cancel this exact proposal.').click()
            dialog.get_by_role('button', name='Confirm cancellation').click()
            expect(page.locator('.approval-row')).to_have_count(0, timeout=15000)
            check('stale draft can be cancelled through the server')
            command.fill('search equipment'); command.press('Enter')
            expect(page.get_by_role('dialog')).to_contain_text('Searches permitted records')
            check('explicit search stays distinct from asking')
            page.keyboard.press('Escape')
            # A real server proposal, approved through the existing ledger.
            event = store.desk_state(keys['owner'])['events'][0]
            store.propose_from_evidence(keys['owner'], {'event_seq': event['seq'], 'text': 'Synthetic crew update for review.', 'request_id': 'console-approval'})
            row = page.locator('.approval-row').filter(has_text='Local message draft')
            expect(row).to_be_visible(timeout=15000)
            check('pending server proposal appears in approvals')
            row.get_by_role('button', name='Review Local message draft').click()
            dialog = page.get_by_role('dialog')
            expect(dialog).to_contain_text('Synthetic crew update for review.')
            approve = dialog.get_by_role('button', name='Approve exact text')
            check('approval requires explicit consent', approve.is_disabled())
            dialog.get_by_text('I approve this exact text and nothing else.').click()
            approve.click()
            expect(page.get_by_role('status').filter(has_text='Nothing is sent')).to_be_visible()
            deadline = time.time() + 15
            while time.time() < deadline and store.desk_state(keys['owner'])['actions'][0]['state'] != 'verified':
                time.sleep(.2)
            check('approved action is executed and verified by the existing outbox', store.desk_state(keys['owner'])['actions'][0]['state'] == 'verified')
            expect(page.locator('.approval-row')).to_have_count(0, timeout=15000)
            check('approvals list reflects the server result')
            # M04: remember this, review it, then an approved create-only inbox note.
            policy = IdentityPolicy(store)
            for capability in ('read', 'inbox.write'):
                policy.grant(keys['owner'], 'demo-source', capability, store.now() + 3600, policy.view(keys['owner'])['epoch'])
            expect(page.locator('.toast')).to_contain_text('Access changed', timeout=15000)
            check('a grant change is announced and rebuilds the view')
            command.fill('When is the camera collection confirmed?'); command.press('Enter')
            ask = page.get_by_role('dialog')
            equipment = ask.locator('.evidence').filter(has_text='Equipment check')
            expect(equipment).to_be_visible(timeout=15000)
            equipment.get_by_role('button', name='Remember this…').click()
            form = ask.get_by_label('Remember this', exact=True)
            form.get_by_label('Record').select_option('new')
            form.get_by_label('Name').fill('Camera collection')
            form.get_by_label('Kind').select_option('commitment')
            form.get_by_label('Statement').select_option('status')
            form.get_by_label('Value').fill('needs confirmation')
            form.get_by_label('Memory type').select_option('commitment')
            form.get_by_label('Retention').select_option(label='90 days')
            form.get_by_role('button', name='Preview proposal').click()
            preview = ask.get_by_label('Remember this preview')
            expect(preview).to_contain_text('Forgotten after', timeout=15000)
            page.screenshot(path=str(out / 'connected-remember.png'))
            check('remember previews workspace, type, source and retention', all(x in preview.inner_text() for x in ('demo-production', 'commitment', 'notes/Equipment.md')))
            check('a captured proposal is not usable before review', not any(c['usable'] for c in memory.view(keys['owner'])['claims'] if c.get('memory_type') == 'commitment'))
            preview.get_by_role('button', name='Accept as my reviewed statement').click()
            expect(preview).to_contain_text('Accepted as your reviewed statement')
            check('accepting makes the captured statement usable', any(c['usable'] for c in memory.view(keys['owner'])['claims'] if c.get('memory_type') == 'commitment'))
            preview.locator('summary').click()
            preview.get_by_label('Inbox note name').fill('Camera collection.md')
            preview.get_by_role('button', name='Propose inbox note').click()
            expect(page.get_by_role('status').filter(has_text='Inbox note proposed')).to_be_visible()
            target = home / 'vault' / 'ALFRED' / 'Inbox' / 'Camera collection.md'
            check('nothing is written before approval', not target.exists())
            ask.get_by_label('Close panel').click()
            row = page.locator('.approval-row').filter(has_text='Inbox note · Camera collection.md')
            expect(row).to_be_visible(timeout=15000)
            row.get_by_role('button', name='Review Inbox note · Camera collection.md').click()
            dialog = page.get_by_role('dialog')
            expect(dialog).to_contain_text('ALFRED/Inbox/Camera collection.md')
            dialog.get_by_text('I approve creating this exact file with this exact text.').click()
            dialog.get_by_role('button', name='Approve exact text').click()
            deadline = time.time() + 15
            while time.time() < deadline and not target.exists():
                time.sleep(.2)
            check('approved inbox note is created in the vault', target.exists() and 'needs confirmation' in target.read_text())
            expect(page.locator('.approval-row')).to_have_count(0, timeout=15000)
            page.get_by_label('Search workspace', exact=True).click()
            page.get_by_label('Search records').fill('Camera collection')
            expect(page.get_by_role('dialog').locator('.record-row').filter(has_text='Camera collection')).to_have_count(2, timeout=15000)
            check('the new inbox note is indexed and read back as an authored note beside the reviewed record')
            page.keyboard.press('Escape')
            # Stage D: executive records shared by the panel and the graph.
            import datetime
            command.fill('tasks'); command.press('Enter')
            tasks = page.get_by_role('dialog')
            form = tasks.get_by_label('New executive record')
            form.get_by_label('Kind').select_option('milestone')
            form.get_by_label('Project').select_option(label='Sample film')
            form.get_by_label('Title').fill('Picture lock')
            form.get_by_role('button', name='Add record').click()
            expect(tasks.locator('.task-row').filter(has_text='Picture lock')).to_be_visible(timeout=15000)
            tomorrow = (datetime.date.today() + datetime.timedelta(days=1)).isoformat()
            form.get_by_label('Kind').select_option('commitment')
            form.get_by_label('Project').select_option(label='Sample film')
            form.get_by_label('Title').fill('Send the crew update')
            form.get_by_label('Due').fill(tomorrow)
            form.get_by_role('button', name='Add record').click()
            expect(tasks.locator('.task-row').filter(has_text='Send the crew update')).to_be_visible(timeout=15000)
            tasks.get_by_label('Close panel').click()
            projects = page.locator('.executive-panel .project-row').filter(has_text='Sample film')
            expect(projects.first).to_contain_text('0/1 milestones', timeout=15000)
            check('project progress comes from recorded milestones only')
            recommendation = page.locator('.recommendation-row').filter(has_text='Send the crew update')
            expect(recommendation).to_contain_text('Recommendation · due within seven days commitment')
            check('a due-soon commitment is shown as a labelled recommendation, not a priority', page.locator('.executive-panel .priority-row').count() == 0)
            recommendation.get_by_role('button', name='Accept Send the crew update as a priority').click()
            priority = page.locator('.executive-panel .priority-row').filter(has_text='Send the crew update')
            expect(priority).to_be_visible(timeout=15000)
            check('accepting a recommendation makes it a priority the person owns', page.locator('.recommendation-row').count() == 0)
            page.screenshot(path=str(out / 'connected-executive.png'))
            priority.click()
            expect(priority).to_have_attribute('aria-checked', 'true', timeout=15000)
            check('completing a priority is recorded on the server')
            command.fill('tasks'); command.press('Enter')
            tasks.locator('.task-row').filter(has_text='Picture lock').click()
            expect(tasks.locator('.task-row').filter(has_text='Picture lock')).to_have_attribute('aria-checked', 'true', timeout=15000)
            tasks.get_by_label('Close panel').click()
            expect(projects.first).to_contain_text('1/1 milestones', timeout=15000)
            check('completing a milestone updates project progress')
            page.get_by_role('button', name='Explore operations').click()
            page.get_by_role('dialog').locator('.record-row').filter(has_text='Picture lock').click()
            expect(inspector).to_contain_text('EXECUTIVE RECORD · AUTHORED BY YOU')
            expect(inspector).to_contain_text('executive link · for project')
            check('executive records are graph records with a labelled link to their project')
            page.get_by_label('Close record inspector').click()
            # Bounded jobs: run on the exact revision being inspected, follow events, leave and return.
            film_text = (home / 'vault' / 'projects' / 'Sample Film.md').read_text()
            page.get_by_role('button', name='Explore projects').click()
            page.get_by_role('dialog').get_by_role('button', name=re.compile(r'^Sample film The fictional')).click()
            run = inspector.locator('.run-job')
            expect(run).to_contain_text('Runs locally on revision')
            run.get_by_label('Job kind').select_option('word_count')
            run.get_by_role('button', name='Run on this revision').click()
            jobs_dialog = page.get_by_role('dialog')
            expect(jobs_dialog.get_by_role('heading', name='Bounded jobs')).to_be_visible()
            expect(jobs_dialog.locator('.job-follow h3')).to_contain_text('Word and line count · Finished', timeout=20000)
            events = jobs_dialog.get_by_label('Job events').inner_text()
            check('a job submitted from the inspector shows its server events in order',
                  [x in events for x in ('Submitted', 'Assigned to the local worker', 'Started in a local subprocess', 'Finished and result stored')] == [True] * 4
                  and events.index('Submitted') < events.index('Started in a local subprocess') < events.index('Finished and result stored'))
            result = jobs_dialog.get_by_label('Job result')
            expect(result.locator('.detail-list > div').filter(has_text='Words').locator('dd')).to_have_text(f'{len(film_text.split()):,}')
            check('the result is the exact deterministic count, labelled as not an interpretation', 'not an interpretation' in result.inner_text())
            check('the panel states the honest backend', 'not a sandbox' in jobs_dialog.inner_text())
            before = len(job_requests); page.wait_for_timeout(3000)
            check('a finished job is not polled again', len(job_requests) - before <= 1)
            page.screenshot(path=str(out / 'connected-jobs.png'))
            jobs_dialog.get_by_label('Close panel').click()
            run.get_by_label('Job kind').select_option('summarise_lines')
            run.get_by_label('Number of lines').fill('3')
            run.get_by_role('button', name='Run on this revision').click()
            expect(jobs_dialog.locator('.job-follow h3')).to_contain_text('First lines (extractive)', timeout=20000)
            jobs_dialog.get_by_label('Close panel').click()
            # Leave entirely: reload the page, then come back to the jobs panel.
            page.reload()
            expect(page.locator('.connection-state')).to_have_text('Connected', timeout=15000)
            command.fill('jobs'); command.press('Enter')
            jobs_dialog = page.get_by_role('dialog')
            expect(jobs_dialog.locator('.job-row')).to_have_count(2, timeout=15000)
            jobs_dialog.locator('.job-row').filter(has_text='First lines (extractive)').click()
            expect(jobs_dialog.locator('.job-follow h3')).to_contain_text('First lines (extractive) · Finished', timeout=20000)
            extracted = jobs_dialog.get_by_label('Extracted lines').locator('li')
            expect(extracted).to_have_count(3)
            check('after leaving and reloading, the job and its result are read back from the server')
            first_lines = [line.strip()[:200] for line in film_text.splitlines() if line.strip()][:3]
            check('extracted lines are the exact first lines of the note, not a summary', extracted.all_inner_texts() == first_lines)
            jobs_dialog.get_by_label('Close panel').click()
            # RUN-001: the host's own report, and the owner's pause control.
            command.fill('settings'); command.press('Enter')
            health = page.get_by_role('dialog').get_by_role('region', name='Host health')
            expect(health).to_contain_text(re.compile(r'ready · [0-9]+ notes'), timeout=15000)
            check('the console shows what the host is doing and that it is not an installed service', 'not an installed service' in health.inner_text())
            health.get_by_role('button', name='Pause ALFRED').click()
            health.get_by_role('group', name='Confirm pause').get_by_role('button', name='Pause now').click()
            expect(health).to_contain_text('Paused', timeout=15000)
            check('pausing is a confirmed owner action reported back by the host')
            page.get_by_role('dialog').get_by_label('Close panel').click()
            command.fill('What still needs confirming?'); command.press('Enter')
            expect(page.get_by_role('dialog')).to_contain_text('ALFRED is paused', timeout=15000)
            check('a paused host refuses new questions and says why')
            page.get_by_role('dialog').get_by_label('Close panel').click()
            command.fill('settings'); command.press('Enter')
            page.get_by_role('dialog').get_by_role('region', name='Host health').get_by_role('button', name='Resume ALFRED').click()
            expect(page.get_by_role('status').filter(has_text='ALFRED resumed')).to_be_visible(timeout=15000)
            check('the owner resumes the host from the console')
            page.get_by_role('dialog').get_by_label('Close panel').click()
            # Laptop and mobile layouts.
            for width, height in ((1280, 800), (390, 844)):
                page.set_viewport_size({'width': width, 'height': height}); page.wait_for_timeout(600)
                check(f'{width}px has no horizontal overflow', page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
                page.screenshot(path=str(out / f'connected-{width}.png'), full_page=True)
            page.set_viewport_size({'width': 1648, 'height': 928})
            check('no browser storage used', page.evaluate('localStorage.length===0&&sessionStorage.length===0'))
            check('no access key rendered', keys['owner'] not in page.content())
            # Server loss keeps the last confirmed view labelled, never fixtures.
            port = server.server_port
            server.shutdown(); server.server_close()
            page.wait_for_timeout(9500)
            expect(page.locator('.connection-state')).to_have_text('Unreachable', timeout=10000)
            expect(page.locator('.connection-banner')).to_contain_text('last confirmed')
            check('command caption no longer claims a live connection', 'UNREACHABLE' in page.locator('.command-meta').inner_text())
            check('server loss is shown as unreachable with last confirmation time')
            check('server loss never substitutes fixtures', 'Velvet Accademy' not in page.locator('body').inner_text())
            page.screenshot(path=str(out / 'connected-unreachable.png'))
            # A restarted server keeps no in-memory sessions, so the console asks to sign in again.
            server = DeskHTTPServer(store, sup, port=port, console_dist=DIST, jobs=jobs)
            thread = threading.Thread(target=server.serve_forever, kwargs={'poll_interval': .01}, daemon=True); thread.start()
            expect(page.get_by_role('heading', name='Sign in to ALFRED')).to_be_visible(timeout=20000)
            check('a restarted server requires a new sign-in and clears the stale view', '0 records' in page.locator('.graph-view-label').inner_text())
            page.get_by_label('Access key').fill(keys['owner']); page.get_by_role('button', name='Sign in').click()
            expect(page.locator('.connection-state')).to_have_text('Connected')
            # M02: the owner manages grants and invites another person, from the console.
            page.get_by_role('button', name='Data and permissions').click()
            security = page.get_by_role('dialog')
            expect(security).to_contain_text('Explicit grants', timeout=15000)
            model_switch = security.get_by_role('switch', name='Model for Local Markdown vault')
            check('the model capability starts ungranted', model_switch.get_attribute('aria-checked') == 'false')
            model_switch.click()
            expect(model_switch).to_have_attribute('aria-checked', 'true', timeout=15000)
            check('the owner grants a capability and the access panel stays open', security.is_visible())
            security.get_by_role('button', name='Create one-time code').click()
            expect(security.get_by_label('One-time code', exact=True).locator('.hash')).to_be_visible(timeout=15000)
            invitation = security.get_by_label('One-time code', exact=True).locator('.hash').inner_text().strip()
            check('a one-time invitation code is created', len(invitation) == 24)
            # M02 pairing: a second device for the same person gets its own key; no key is copied.
            security.get_by_label('Role for the new device').select_option('reader')
            security.get_by_role('button', name='Create pairing code').click()
            expect(security.get_by_label('Pairing code', exact=True).locator('.hash')).to_be_visible(timeout=15000)
            pairing = security.get_by_label('Pairing code', exact=True).locator('.hash').inner_text().strip()
            check('a single-use pairing code is created for a reader device', len(pairing) == 24)
            device = browser.new_context(viewport={'width': 1280, 'height': 800}, device_scale_factor=1)
            tablet = device.new_page()
            tablet.on('pageerror', lambda e: page_errors.append(str(e)))
            tablet.on('request', lambda r: foreign.append(r.url) if not r.url.startswith(server.origin) else None)
            tablet.goto(server.origin + '/console/')
            tablet.get_by_role('button', name='Pair this device with a code').click()
            tablet.get_by_label('Pairing code').fill(pairing)
            tablet.get_by_label('Device name').fill('Fictional tablet')
            tablet.screenshot(path=str(out / 'connected-pairing.png'))
            tablet.get_by_role('button', name='Pair this device').click()
            paired = tablet.get_by_role('group', name='Device paired')
            expect(paired).to_be_visible(timeout=15000)
            tablet_key = paired.get_by_label("This device's access key").inner_text().strip()
            check('the new device receives its own key, shown once', len(tablet_key) == 43 and tablet_key not in keys.values())
            check('continuing requires confirming the key is kept', paired.get_by_role('button', name='Continue to ALFRED').is_disabled())
            paired.get_by_label('I have stored this key privately.').check()
            paired.get_by_role('button', name='Continue to ALFRED').click()
            expect(tablet.locator('.connection-state')).to_have_text('Connected', timeout=15000)
            expect(tablet.locator('.graph-view-label')).to_have_text(re.compile(r'[1-9][0-9]* records'), timeout=15000)
            check("the paired device reads with the same person's grants and no longer shows its key", tablet_key not in tablet.content())
            check('the paired device has reader authority only', 'reader' in tablet.evaluate("fetch('/desk/session').then(r=>r.json()).then(j=>j.role)"))
            security.get_by_label('Close panel').click()
            page.get_by_role('button', name='Data and permissions').click()
            security = page.get_by_role('dialog')
            expect(security.locator('.device-row').filter(has_text='Fictional tablet')).to_contain_text('reader', timeout=15000)
            check('the owner sees the paired device in their own device list')
            security.locator('.device-row').first.scroll_into_view_if_needed()
            page.screenshot(path=str(out / 'connected-devices.png'))
            security.get_by_role('button', name='Revoke Fictional tablet').click()
            expect(page.get_by_role('status').filter(has_text='Fictional tablet can no longer sign in')).to_be_visible(timeout=15000)
            expect(tablet.get_by_role('heading', name='Sign in to ALFRED')).to_be_visible(timeout=20000)
            check('revoking a device signs it out and clears its records', '0 records' in tablet.locator('.graph-view-label').inner_text())
            expect(page.locator('.connection-state')).to_have_text('Connected')
            check('revoking another device leaves this device connected', security.is_visible())
            device.close()
            security.get_by_label('Close panel').click()
            # Revocation clears everything without a reload.
            page.get_by_role('button', name='Explore projects').click()
            store.revoke('demo-owner')
            expect(page.get_by_role('heading', name='Sign in to ALFRED')).to_be_visible(timeout=15000)
            check('revocation returns to sign-in and closes open dialogs', page.get_by_role('dialog').count() == 0)
            check('revocation clears every record', '0 records' in page.locator('.graph-view-label').inner_text() and 'Sample film' not in page.locator('body').inner_text())
            # Under strict grants another person sees nothing until granted. Counts leak nothing.
            page.get_by_label('Access key').fill(keys['reader']); page.get_by_role('button', name='Sign in').click()
            expect(page.locator('.connection-state')).to_have_text('Connected')
            expect(page.locator('.graph-view-label')).to_contain_text('0 records')
            check('a person without grants sees no records, names or counts', 'Sample film' not in page.locator('body').inner_text())
            command.fill('jobs'); command.press('Enter')
            expect(page.get_by_role('dialog')).to_contain_text('No jobs you can see.', timeout=15000)
            check('without a read grant a person sees no job history for that source')
            page.get_by_role('dialog').get_by_label('Close panel').click()
            page.get_by_role('button', name='Data and permissions').click()
            security = page.get_by_role('dialog')
            expect(security).to_contain_text('You hold no grants yet')
            security.get_by_label('One-time code').fill(invitation)
            security.get_by_role('button', name='Redeem').click()
            expect(page.get_by_role('status').filter(has_text='Code redeemed')).to_be_visible(timeout=15000)
            security.get_by_label('Close panel').click()
            expect(page.locator('.graph-view-label')).to_have_text(re.compile(r'[1-9][0-9]* records'), timeout=15000)
            check('redeeming an invitation grants exactly what it names to the person who redeems it', page.get_by_role('button', name='Explore projects').is_visible())
            command.fill('jobs'); command.press('Enter')
            expect(page.get_by_role('dialog').locator('.job-row')).to_have_count(2, timeout=15000)
            check('a read grant makes the job history for that source visible')
            page.get_by_role('dialog').get_by_label('Close panel').click()
            page.get_by_role('button', name='Explore projects').click()
            page.get_by_role('dialog').get_by_role('button', name=re.compile(r'^Sample film The fictional')).click()
            expect(inspector).to_contain_text('projects/Sample Film.md', timeout=15000)
            check('a reader can inspect the note but cannot submit jobs', inspector.locator('.run-job').count() == 0)
            # M05: removing a whole source, in a fresh workspace so the flow above is unaffected.
            # The first page is finished; closing it keeps two software-rendered scenes from competing.
            context.close()
            home2 = root / 'demo-remove'; keys2 = init_demo(home2)
            # MEM-014 and CON-001 in the same fresh workspace: a Syncthing conflict copy beside a
            # note, and one imported calendar export under explicit grants.
            film = home2 / 'vault' / 'projects' / 'Sample Film.md'
            copy_name = 'Sample Film.sync-conflict-20261002-101500-ABCDEFG.md'
            (film.parent / copy_name).write_text(film.read_text() + '\nEdited on another device.\n')
            store2 = KnowledgeStore(home2 / 'desk.sqlite')
            sup2 = KnowledgeSupervisor(store2, keys2['owner'], keys2['source'], home2 / 'project', vault=home2 / 'vault', interval=.2)
            sup2.cycle()
            policy2 = IdentityPolicy(store2); policy2.enable(keys2['owner'], 0)
            policy2.grant(keys2['owner'], 'demo-source', 'read', store2.now() + 3600, policy2.view(keys2['owner'])['epoch'])
            from alfred import connectors
            calendar_instance = connectors.create_instance(store2, keys2['owner'], 'ics-export', 'Calendar export')
            export_file = root / 'calendar.ics'
            export_file.write_bytes('\r\n'.join(['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Example//Synthetic//EN', 'BEGIN:VEVENT',
                                                  'UID:review-1@example.org', 'DTSTAMP:20261001T120000Z', 'DTSTART;TZID=Europe/London:20261014T090000',
                                                  'SUMMARY:Fictional planning review', 'END:VEVENT', 'END:VCALENDAR', '']).encode())
            connectors.run_import(store2, keys2['owner'], calendar_instance['bearer'], export_file)
            sup2.start()
            server2 = DeskHTTPServer(store2, sup2, port=0, console_dist=DIST)
            thread2 = threading.Thread(target=server2.serve_forever, kwargs={'poll_interval': .01}, daemon=True); thread2.start()
            try:
                removal = browser.new_context(viewport={'width': 1648, 'height': 928}, device_scale_factor=1, reduced_motion='reduce')
                remover = removal.new_page()
                remover.on('pageerror', lambda e: page_errors.append(str(e)))
                remover.on('console', lambda m: console_messages.append(f'{m.type}: {m.text}'))
                remover.goto(server2.origin + '/console/')
                remover.get_by_label('Access key').fill(keys2['owner']); remover.get_by_role('button', name='Sign in').click()
                expect(remover.locator('.graph-view-label')).to_contain_text('23 records', timeout=15000)
                check('the conflict copy is not a record: 20 notes, 2 sources, 1 imported item')
                remover.get_by_role('button', name='Explore projects').click()
                remover.get_by_role('dialog').get_by_role('button', name=re.compile(r'^Sample film The fictional')).click()
                source_inspector = remover.get_by_role('complementary', name='Record inspector')
                conflict = source_inspector.get_by_role('region', name='Sync conflict')
                expect(conflict).to_contain_text(copy_name, timeout=15000)
                check('the note shows its sync conflict copy and the tool that made it', 'Syncthing' in conflict.inner_text() and 'never merges' in conflict.inner_text())
                remover.screenshot(path=str(out / 'connected-sync-conflict.png'))
                remover.get_by_label('Command or search').fill('search Fictional planning'); remover.get_by_label('Command or search').press('Enter')
                remover.get_by_role('dialog').get_by_role('button', name=re.compile(r'^Fictional planning review')).click()
                expect(source_inspector).to_contain_text('IMPORTED EXPORT · UNCHECKED REPORT', timeout=15000)
                check('an imported calendar item is labelled as an unchecked export report, not an authored note')
                remover.get_by_label('Close record inspector').click()
                remover.get_by_role('button', name='Data and permissions').click()
                access = remover.get_by_role('dialog')
                connector_list = access.get_by_role('region', name='Export connectors')
                expect(connector_list).to_contain_text('Current snapshot', timeout=15000)
                check('the access panel shows the connector, its freshness and item count', '1 item' in connector_list.inner_text())
                import_switch = access.get_by_role('switch', name='Import for Calendar export')
                check('the owner sees the import grant as its own switch', import_switch.get_attribute('aria-checked') == 'true')
                check('a connector source offers no inbox writing', access.get_by_role('switch', name='Inbox notes for Calendar export').count() == 0)
                remover.screenshot(path=str(out / 'connected-connectors.png'))
                access.get_by_label('Close panel').click()
                remover.get_by_role('button', name='Explore sources').click()
                remover.get_by_role('dialog').locator('.record-row').filter(has_text='Local Markdown vault').click()
                expect(source_inspector.get_by_role('region', name='Sync conflict copies')).to_contain_text('beside its original', timeout=15000)
                check('the source lists its conflict copies')
                expect(source_inspector).to_contain_text('SELECTED SOURCE', timeout=15000)
                source_inspector.get_by_role('button', name='Remove this source from ALFRED').click()
                confirm = source_inspector.get_by_role('group', name='Confirm source removal')
                check('removing a source needs explicit consent', confirm.get_by_role('button', name='Remove source').is_disabled())
                consent = confirm.get_by_label('I want to remove this source and everything derived from it.')
                consent.check()
                # The workspace changes while the person is confirming, so the console re-reads the
                # open record; the open confirmation and its consent must survive that refresh.
                with remover.expect_response(lambda r: '/desk/console/records/source:' in r.url, timeout=30000):
                    equipment = home2 / 'vault' / 'notes' / 'Equipment.md'
                    equipment.write_text(equipment.read_text() + '\nChecked again before the source was removed.\n')
                check('a refresh while confirming keeps the open confirmation and its consent', confirm.is_visible() and consent.is_checked())
                confirm.get_by_role('button', name='Remove source').click()
                expect(remover.get_by_role('status').filter(has_text='Source removed: 20 notes')).to_be_visible(timeout=15000)
                remover.screenshot(path=str(out / 'connected-source-removed.png'))
                expect(remover.locator('.graph-view-label')).to_contain_text(re.compile(r'(^|[^0-9])2 records'), timeout=15000)
                check('removing a source clears its records, leaving the other source, with a receipt')
                check("the person's own files are untouched", (home2 / 'vault' / 'projects' / 'Sample Film.md').is_file())
                check('the removal is journalled for restore', '"source_forgotten"' in (home2 / 'desk.sqlite.lifecycle.jsonl').read_text())
                removal.close()
            finally:
                sup2.stop()
                server2.shutdown(); server2.server_close()
            csp = [m for m in console_messages if 'Content Security Policy' in m or 'Refused to' in m]
            check('no Content Security Policy violations', not csp)
            check('no requests leave the loopback origin', not foreign)
            check('no uncaught page errors', not page_errors)
            browser.close()
    finally:
        sup.stop(); halt_jobs()
        try:
            server.shutdown(); server.server_close()
        except Exception:
            pass

report = {'passed': len(checks), 'checks': checks, 'browser_console': console_messages[-20:], 'page_errors': page_errors,
          'inputs': 'synthetic Markdown vault only', 'model_inference': False, 'console_dist': 'console/dist built from this commit'}
(out / 'browser-report.json').write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps({'passed': len(checks), 'page_errors': page_errors}))
