import {useCallback,useEffect,useMemo,useReducer,useRef,useState} from 'react';
import {AnimatePresence,MotionConfig,motion,useReducedMotion} from 'motion/react';
import {User,Briefcase,Crosshair,MagnifyingGlass,GearSix,ArrowRight,CaretRight,Waveform,Command,Pause,Play,ArrowsOut,X,FileText,Check,WarningCircle,ArrowUpRight,DotsThree,ShareNetwork,Cube,LinkSimple,DownloadSimple,FadersHorizontal,SpeakerSlash,ShieldCheck} from '@phosphor-icons/react';
import {KnowledgeSphere} from './scene/KnowledgeSphere';
import {Dialog} from './components/Dialog';
import {CATEGORIES,SCOPES,categoryCopy,initialState,reducer,scopedRecords,searchRecords,visibleRelationships,type Category,type KnowledgeRecord,type Scope} from './domain/model';
import {createDemoSnapshot} from './domain/fixtures';
import './styles.css';
const NAV=[{id:'personal',label:'Personal',Icon:User},{id:'work',label:'Work',Icon:Briefcase},{id:'operation',label:'Operation',Icon:Crosshair},{id:'research',label:'Research',Icon:MagnifyingGlass},{id:'systems',label:'Systems',Icon:GearSix}] as const;
const scopeHeadlines:Record<Scope,[string,string,string]>={personal:['Clarity','creates','leverage.'],work:['Make','the work','matter.'],operation:['Clear intent.','Deliberate','action.'],research:['Find signal.','Build','understanding.'],systems:['Quietly','capable.','Under control.']};
const scopeSub:Record<Scope,string>={personal:'Your knowledge.\nYour actions.\nA more capable tomorrow.',work:'The details, connected.\nThe direction, clear.',operation:'Your context.\nYour authority.\nNothing assumed.',research:'Sources before certainty.\nEvidence before action.',systems:'Know what is connected.\nKnow what is not.'};
type Modal='brief'|'search'|'review'|'settings'|'voice'|'handoff'|'tasks'|'records'|null;
function downloadJSON(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function RecordIcon({category}:{category:Category}){const Icon={projects:Cube,sources:FileText,knowledge:ShareNetwork,people:User,operations:Crosshair,resources:GearSix}[category];return <Icon size={19}/>;}
function PanelHead({title,count,action,onAction}:{title:string;count?:number;action?:string;onAction?:()=>void}){return <header className="panel-head"><h2>{title}{count!==undefined&&<span className="count">{count}</span>}</h2>{action&&<button onClick={onAction}>{action}<CaretRight size={12}/></button>}</header>;}
export default function App(){
 const[state,dispatch]=useReducer(reducer,undefined,()=>initialState(createDemoSnapshot()));
 const[modal,setModal]=useState<Modal>(null),[query,setQuery]=useState(''),[command,setCommand]=useState(''),[proposalId,setProposalId]=useState<string|null>(null),[reviewConsent,setReviewConsent]=useState(false),[notice,setNotice]=useState(''),[renderer,setRenderer]=useState('Starting graphics'),[clock,setClock]=useState(new Date());
 const systemReduced=useReducedMotion(),inputRef=useRef<HTMLInputElement>(null),searchRef=useRef<HTMLInputElement>(null);
 const reduced=Boolean(systemReduced)||state.reducedMotion;
 const records=useMemo(()=>scopedRecords(state.snapshot,state.scope),[state.snapshot,state.scope]);
 const shownRecords=useMemo(()=>scopedRecords(state.snapshot,state.scope,state.category),[state.snapshot,state.scope,state.category]);
 const selected=records.find(r=>r.id===state.selected);
 const relationships=useMemo(()=>visibleRelationships(state.snapshot,state.scope),[state.snapshot,state.scope]);
 const priorities=state.snapshot.priorities.filter(p=>p.scope===state.scope),proposals=state.snapshot.proposals.filter(p=>p.scope===state.scope),pending=proposals.filter(p=>p.status==='pending');
 const activeProposal=proposals.find(p=>p.id===proposalId),projects=records.filter(r=>r.category==='projects');
 const results=useMemo(()=>searchRecords(state.snapshot,state.scope,query),[state.snapshot,state.scope,query]);
 const onStatus=useCallback((status:string)=>setRenderer(status),[]),selectRecord=useCallback((id:string)=>dispatch({type:'select',id}),[]);
 const switchScope=(scope:Scope)=>{dispatch({type:'scope',scope});setModal(null);setQuery('');};
 const openReview=(id:string)=>{setProposalId(id);setReviewConsent(false);setModal('review');};
 const openCategory=(category:Category)=>{dispatch({type:'category',category});setModal('records');};
 const closeModal=()=>setModal(null);
 useEffect(()=>{const t=setInterval(()=>setClock(new Date()),30000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setQuery('');setModal('search');}if(e.key==='Escape'&&!modal)dispatch({type:'select',id:null});};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[modal]);
 useEffect(()=>{if(modal==='search')searchRef.current?.focus();},[modal]);
 const runCommand=(text:string)=>{const cleaned=text.trim().slice(0,500);if(!cleaned){inputRef.current?.focus();return;}setCommand('');if(/^(brief|summari[sz]e|summari[sz]e today|today|\/brief)$/i.test(cleaned)){setModal('brief');return;}if(/^(plan|tasks|\/tasks)$/i.test(cleaned)){setModal('tasks');return;}if(/^(settings|controls|\/settings)$/i.test(cleaned)){setModal('settings');return;}if(/^(build|handoff|\/handoff)$/i.test(cleaned)){setModal('handoff');return;}const target=SCOPES.find(s=>cleaned.toLowerCase()===s);if(target){switchScope(target);return;}setQuery(cleaned.replace(/^search\s+/i,''));setModal('search');};
 function recordRows(items:KnowledgeRecord[]){return items.length?<div className="record-list">{items.map(r=><button key={r.id} className="record-row" onClick={()=>{selectRecord(r.id);setModal(null);}}><span className="record-symbol"><RecordIcon category={r.category}/></span><span><strong>{r.title}</strong><small>{r.summary}</small></span><CaretRight size={16}/></button>)}</div>:<div className="empty-state"><ShareNetwork size={28}/><h3>No matching records.</h3><p>Try a shorter search or choose another workspace. No records are inferred to fill this view.</p></div>;}
 const formatTime=(zone?:string)=>new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',...(zone?{timeZone:zone}:{})}).format(clock);
 return <MotionConfig reducedMotion={reduced?'always':'user'}><div className={`console ${state.focus?'focus-mode':''}`}>
 <a className="skip-link" href="#workspace">Skip to workspace</a>
 <aside className="navigation" aria-label="Workspace navigation"><button className="brand" onClick={()=>{switchScope('personal');dispatch({type:'select',id:null});}} aria-label="ALFRED home"><img src="./mark.svg" alt=""/><strong>ALFRED</strong><span>THINK FURTHER</span></button><nav>{NAV.map(({id,label,Icon})=><button key={id} className={`nav-item ${state.scope===id?'active':''}`} aria-current={state.scope===id?'page':undefined} onClick={()=>switchScope(id)}><Icon size={19} weight={state.scope===id?'fill':'regular'}/><span>{label}</span>{state.scope===id&&<i className="status-dot amber"/>}</button>)}</nav><div className="nav-manifesto"><i className="gold-rule"/><p>Intelligence<br/>Discipline<br/>Leverage<br/>A better<br/>tomorrow.</p></div><div className="nav-bottom"><button className="nav-control" onClick={()=>setModal('settings')}><FadersHorizontal size={17}/><span>Controls</span></button><div className="local-state"><i className="status-dot muted"/>DESIGN BUILD</div><dl><div><dt>DATA</dt><dd>DEMONSTRATION</dd></div><div><dt>BRAIN</dt><dd>NOT CONNECTED</dd></div></dl><span className="build-number">OBSIDIAN / 0.1</span></div></aside>
 <main id="workspace" className="workspace"><header className="topbar"><div><h1>INTELLIGENCE CONSOLE</h1><p><i/>KNOWLEDGE IN CONTEXT <span>/</span> UNDER YOUR AUTHORITY</p></div><div className="topbar-actions"><button aria-label="Search workspace" title="Search (Ctrl or Command + K)" onClick={()=>{setQuery('');setModal('search');}}><MagnifyingGlass size={17}/><kbd>⌘ K</kbd></button><button aria-label={state.focus?'Exit focus mode':'Enter focus mode'} title="Focus view" aria-pressed={state.focus} onClick={()=>dispatch({type:'focus'})}><ArrowsOut size={17}/></button></div></header>
 <section className="stage" aria-label="Intelligence workspace"><div className="intent"><i className="gold-rule"/><AnimatePresence mode="wait"><motion.div key={state.scope} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.3}}><h2>{scopeHeadlines[state.scope].map(line=><span key={line}>{line}</span>)}</h2><p>{scopeSub[state.scope]}</p></motion.div></AnimatePresence><i className="gold-rule lower-rule"/></div><div className="sphere-stage"><KnowledgeSphere records={records} relationships={relationships} selected={state.selected} onSelect={selectRecord} paused={state.paused} reducedMotion={reduced} quality={state.quality} onStatus={onStatus}/><div className="category-labels">{CATEGORIES.map(category=><button key={category} className={`category-label category-${category} ${state.category===category?'selected':''}`} onClick={()=>openCategory(category)} aria-label={`Explore ${category}`}><span className="category-target"><i/></span><span className="category-text"><strong>{category}</strong><span className="category-count">{records.filter(r=>r.category===category).length.toString().padStart(2,'0')}</span><small>{categoryCopy[category].subtitle.split(' · ').map(s=><span key={s}>{s}</span>)}</small></span></button>)}</div><div className="sphere-toolbar"><button onClick={()=>dispatch({type:'pause'})} aria-label={state.paused?'Resume sphere motion':'Pause sphere motion'} aria-pressed={state.paused}>{state.paused?<Play size={12}/>:<Pause size={12}/>}</button><span>KNOWLEDGE FIELD</span><span className="tiny-divider"/><span>{records.length} RECORDS</span><button className="browse-records" onClick={()=>{dispatch({type:'category',category:null});setModal('records');}}>Browse<CaretRight size={10}/></button></div></div></section>
 <div className="command-zone"><form className="command-bar" onSubmit={e=>{e.preventDefault();runCommand(command);}}><button type="button" className="voice-button" aria-label="Voice connection information" onClick={()=>setModal('voice')}><Waveform size={28}/></button><label className="sr-only" htmlFor="command-input">Command or search</label><input ref={inputRef} id="command-input" value={command} onChange={e=>setCommand(e.target.value)} maxLength={500} placeholder="How can I help you today?" autoComplete="off"/><button className="send-button" aria-label="Run local command" type="submit"><ArrowRight size={22}/></button></form><div className="command-shortcuts"><button onClick={()=>setModal('brief')}>Summarise</button><button onClick={()=>switchScope('research')}>Research</button><button onClick={()=>setModal('tasks')}>Plan</button><button onClick={()=>setModal('handoff')}>Build</button><button onClick={()=>{setQuery('');setModal('search');}}>Analyse</button><button aria-label="More commands" onClick={()=>setModal('settings')}><DotsThree size={17}/></button></div><div className="command-footnote">LOCAL DEMO COMMANDS <span>·</span> NO MODEL OR MICROPHONE CONNECTED</div></div>
 <footer className="workspace-footer"><span><i className="status-dot amber"/>YOUR CONTEXT. YOUR CONTROL.</span><button onClick={()=>setModal('settings')}>{renderer}<CaretRight size={11}/></button></footer></main>
 <aside className="operations" aria-label="Operational overview"><header className="clock-block"><div><time>{formatTime()}</time><span>{new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(clock).toUpperCase()}</span></div><button onClick={()=>dispatch({type:'focus'})} aria-label="Toggle focus mode">FOCUS<br/>BUILD<br/>EXECUTE<i className="gold-rule"/></button></header><div className="operations-scroll">
 <section className="panel briefing"><PanelHead title="Executive brief" action="Open" onAction={()=>setModal('brief')}/><button className="brief-copy" onClick={()=>setModal('brief')}><span>{pending.length===2?'Two decisions need you.':pending.length===1?'One decision needs you.':'A little more room to think.'}<br/>The rest can wait.</span><ArrowUpRight size={16}/></button><div className="micro-caption">ILLUSTRATIVE BRIEF <i className="status-dot amber"/></div></section>
 <section className="panel focus-panel"><PanelHead title="Operational focus" count={Math.min(3,records.length)}/>{records.slice(0,3).map((r,i)=><button className="focus-row" key={r.id} onClick={()=>selectRecord(r.id)}><i className={`status-dot ${i===0?'amber':i===1?'sage':'muted'}`}/><span><small>{r.category}</small><strong>{r.title}</strong><em>{r.summary}</em></span><CaretRight size={14}/></button>)}</section>
 <section className="panel approvals"><PanelHead title="Awaiting your review" count={pending.length}/>{pending.length?pending.map(p=><button className="approval-row" key={p.id} onClick={()=>openReview(p.id)}><FileText size={19}/><span><strong>{p.title}</strong><small>Example draft · review only</small></span><CaretRight size={13}/></button>):<p className="quiet-empty">Nothing waiting for review.</p>}</section>
 <section className="panel priorities"><PanelHead title="Top priorities" count={priorities.filter(p=>!p.done).length} action="All" onAction={()=>setModal('tasks')}/>{priorities.length?priorities.slice(0,3).map(p=><button role="checkbox" aria-checked={p.done} className={`priority-row ${p.done?'done':''}`} key={p.id} onClick={()=>dispatch({type:'priority',id:p.id})}><span className="check-ring">{p.done&&<Check size={11}/>}</span><span>{p.title}</span><small>{p.timing}</small></button>):<p className="quiet-empty">No sample priorities in this workspace.</p>}</section>
 <section className="panel project-panel"><PanelHead title="Active projects" count={projects.length} action="Open" onAction={()=>openCategory('projects')}/>{projects.length?projects.slice(0,2).map((r,i)=><button key={r.id} className="project-row" onClick={()=>selectRecord(r.id)}><span className={`project-icon project-icon-${i}`}><Cube size={18}/></span><span><strong>{r.title}</strong><small>{r.summary}</small></span><CaretRight size={13}/></button>):<p className="quiet-empty">No projects in this workspace.</p>}</section></div>
 <footer className="operations-footer"><button onClick={()=>setModal('settings')}><ShieldCheck size={20}/><span>CONNECTION STATE<small>Demo only · no live integrations</small></span></button><div className="world-times"><span>LONDON <b>{formatTime('Europe/London')}</b></span><span>UTC <b>{formatTime('UTC')}</b></span></div></footer></aside>
 <AnimatePresence>{selected&&<motion.aside key={selected.id} className="inspector" initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={{opacity:0,x:24}} transition={{duration:.24}} aria-label="Record inspector"><header><span className="eyebrow">{selected.category} / INSPECT</span><button className="icon-button" aria-label="Close record inspector" onClick={()=>dispatch({type:'select',id:null})}><X size={20}/></button></header><div className="inspector-body"><span className="demo-badge">DEMONSTRATION RECORD</span><h2>{selected.title}</h2><p className="inspector-summary">{selected.summary}</p><div className="inspector-section"><h3>Context</h3><p>{selected.detail}</p></div><div className="inspector-section"><h3>Provenance</h3><dl className="detail-list"><div><dt>Source</dt><dd>{selected.provenance.label}</dd></div><div><dt>Revision</dt><dd>{selected.provenance.revision}</dd></div><div><dt>Basis</dt><dd>{selected.provenance.basis}</dd></div><div><dt>Scope</dt><dd>{selected.scope}</dd></div></dl><blockquote>{selected.provenance.excerpt}</blockquote></div><div className="inspector-section"><h3>Explicit relationships</h3>{relationships.filter(e=>e.from===selected.id||e.to===selected.id).length?relationships.filter(e=>e.from===selected.id||e.to===selected.id).map(e=>{const other=records.find(r=>r.id===(e.from===selected.id?e.to:e.from));return <button className="linked-record" key={e.id} onClick={()=>other&&selectRecord(other.id)}><LinkSimple size={17}/><span><small>{e.relation.replaceAll('_',' ')}</small>{other?.title}</span><CaretRight size={14}/></button>;}):<p className="muted-copy">No explicit links in this fixture. Decorative lines are not relationships.</p>}</div><button className="secondary-button export-button" onClick={()=>downloadJSON({mode:'demo',record:selected,relationships:relationships.filter(e=>e.from===selected.id||e.to===selected.id)},`ALFRED-${selected.id}-demo.json`)}><DownloadSimple size={17}/>Export record</button></div></motion.aside>}</AnimatePresence>
 {modal&&<Dialog title={modal==='brief'?'Your briefing':modal==='search'?'Find your signal':modal==='review'?'Review the exact proposal':modal==='settings'?'Console controls':modal==='voice'?'Voice, when it is ready':modal==='handoff'?'One console. A separate brain.':modal==='tasks'?'Your next steps':state.category?categoryCopy[state.category].description.split('.')[0]:'Your knowledge, in context'} subtitle={`${state.scope.toUpperCase()} / ${modal==='review'?'LOCAL DEMONSTRATION':'ALFRED'}`} onClose={closeModal} wide={modal==='handoff'}>
 {modal==='search'&&<><div className="search-box"><MagnifyingGlass size={20}/><input ref={searchRef} aria-label="Search records" placeholder="Search titles, context and categories" value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/><kbd>ESC</kbd></div><p className="dialog-note">Searches the {state.scope} fixtures only. No AI answer is fabricated.</p>{recordRows(results)}<p className="result-count">{results.length} matching records</p></>}
 {modal==='records'&&<><p className="dialog-note">{state.category?categoryCopy[state.category].description:'Every displayed record has an explicit fixture source. The background particle field is decorative.'}</p><div className="filter-chips"><button className={!state.category?'active':''} onClick={()=>dispatch({type:'category',category:null})}>All</button>{CATEGORIES.map(c=><button className={state.category===c?'active':''} onClick={()=>dispatch({type:'category',category:c})} key={c}>{c}</button>)}</div>{recordRows(shownRecords)}</>}
 {modal==='brief'&&<><p className="large-copy">Keep your attention<br/>on what matters next.</p><p className="dialog-note">This is an authored demonstration briefing, not a live assessment or model response.</p><div className="brief-metrics"><span><b>{pending.length}</b>Awaiting review</span><span><b>{priorities.filter(t=>!t.done).length}</b>Open priorities</span><span><b>{records.length}</b>Visible records</span></div>{recordRows(records.slice(0,3))}<button className="primary-button" onClick={()=>setModal('tasks')}>Review next steps<ArrowRight size={16}/></button></>}
 {modal==='tasks'&&<><p className="dialog-note">Check off sample priorities. Changes last for this browser session only.</p>{priorities.length?priorities.map(p=><button role="checkbox" aria-checked={p.done} key={p.id} className={`task-row ${p.done?'done':''}`} onClick={()=>dispatch({type:'priority',id:p.id})}><span className="check-ring">{p.done&&<Check size={13}/>}</span><span>{p.title}</span><small>{p.timing}</small></button>):<p className="quiet-empty">No sample priorities in this workspace.</p>}</>}
 {modal==='review'&&activeProposal&&<><div className="review-scope"><WarningCircle size={20}/><span>Local review demonstration. Nothing is sent or executed.</span></div><h3 className="proposal-title">{activeProposal.title}</h3><p className="proposal-body">{activeProposal.body}</p><dl className="detail-list"><div><dt>Revision</dt><dd>{activeProposal.revision}</dd></div><div><dt>Workspace</dt><dd>{activeProposal.scope}</dd></div><div><dt>Effect</dt><dd>Browser session only</dd></div></dl>{activeProposal.status==='pending'?<><label className="consent"><input type="checkbox" checked={reviewConsent} onChange={e=>setReviewConsent(e.target.checked)}/><span>I have read this exact example. This is not a live approval.</span></label><div className="button-row"><button className="primary-button" disabled={!reviewConsent} onClick={()=>{dispatch({type:'review',id:activeProposal.id,revision:activeProposal.revision,outcome:'reviewed',at:new Date().toISOString()});setNotice('Example marked reviewed. Nothing sent or executed.');setModal(null);}}>Mark reviewed<Check size={16}/></button><button className="secondary-button" onClick={()=>{dispatch({type:'review',id:activeProposal.id,revision:activeProposal.revision,outcome:'declined',at:new Date().toISOString()});setModal(null);setNotice('Example declined. No external effect.');}}>Decline example</button></div></>:<p className="dialog-note">This example is already {activeProposal.status}.</p>}</>}
 {modal==='settings'&&<><div className="settings-row"><span><strong>Graphics quality</strong><small>High uses a denser field and higher pixel resolution.</small></span><select aria-label="Graphics quality" value={state.quality} onChange={e=>dispatch({type:'quality',quality:e.target.value as 'high'|'balanced'})}><option value="high">High</option><option value="balanced">Balanced</option></select></div><div className="settings-row"><span><strong>Reduce motion</strong><small>{systemReduced?'Your operating system requests reduced motion.':'A still sphere. Functional controls remain available.'}</small></span><button className={`toggle ${reduced?'on':''}`} role="switch" aria-checked={reduced} aria-label="Reduce motion" disabled={Boolean(systemReduced)} onClick={()=>dispatch({type:'motion',value:!state.reducedMotion})}><i/></button></div><div className="settings-row"><span><strong>Pause sphere</strong><small>Pause decorative movement without changing data.</small></span><button className={`toggle ${state.paused?'on':''}`} role="switch" aria-checked={state.paused} aria-label="Pause sphere" onClick={()=>dispatch({type:'pause'})}><i/></button></div><div className="connection-list"><h3>Actual connections</h3><div><span>Renderer</span><b>{renderer}</b></div><div><span>Workspace data</span><b>Fictional fixtures</b></div><div><span>Brain / model</span><b>Not connected</b></div><div><span>Microphone</span><b>Off · never requested</b></div><div><span>External accounts</span><b>Not connected</b></div><div><span>Graph</span><b>{records.length} records · {relationships.length} explicit links</b></div></div><div className="button-row"><button className="secondary-button" onClick={()=>downloadJSON({mode:'demo',scope:state.scope,receipts:state.receipts.filter(r=>proposals.some(p=>p.id===r.proposalId))},'ALFRED-demo-receipts.json')}><DownloadSimple size={17}/>Export review receipts</button><button className="text-button" onClick={()=>{dispatch({type:'reset',snapshot:createDemoSnapshot()});setNotice('Demo reset. All example changes cleared.');setModal(null);}}>Reset demo</button></div><p className="dialog-note">No preferences, credentials or records are saved to browser storage. Refreshing resets the demonstration.</p></>}
 {modal==='voice'&&<div className="voice-empty"><SpeakerSlash size={46} weight="thin"/><h3>Nothing is listening.</h3><p>The command rail is ready for a future voice adapter. No audio is captured, no browser permission is requested and no voice service is connected.</p><button className="primary-button" onClick={()=>{setModal(null);setTimeout(()=>inputRef.current?.focus(),50);}}>Use the keyboard<Command size={17}/></button></div>}
 {modal==='handoff'&&<><p className="large-copy">Keep the look.<br/>Connect the intelligence.</p><p className="dialog-note">This frontend is an isolated presentation lane over the ALFRED v0.8 checkpoint. It does not replace the existing Python core or web interface.</p><div className="handoff-grid"><div><span className="eyebrow">PRESENTATION</span><h3>React + TypeScript</h3><p>Workspace navigation, inspection, local search, explicit review states and keyboard interaction.</p></div><div><span className="eyebrow">GRAPHICS</span><h3>Three.js + GLSL</h3><p>React Three Fiber, original particle / shell / star shaders, restrained bloom and quality controls.</p></div><div><span className="eyebrow">INTEGRATION BOUNDARY</span><h3>Typed, not assumed</h3><p>ConsoleSnapshot describes presentation data. It is not an existing backend endpoint. Adapt authenticated, scoped source data deliberately.</p></div><div><span className="eyebrow">AUTHORITY</span><h3>The server decides</h3><p>Preserve exact approvals, source revisions, revocation, result evidence and audit receipts. UI state never grants permission.</p></div></div><div className="review-scope"><ShieldCheck size={20}/><span>Brain integration, real audio and external accounts are separate acceptance gates.</span></div></>}
 </Dialog>}
 <AnimatePresence>{notice&&<motion.div className="toast" role="status" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0}}><Check size={16}/>{notice}</motion.div>}</AnimatePresence>
 </div></MotionConfig>;
}
