'use strict';
// A personal-intelligence shell over the existing source and authority boundaries.
// No inferred permission, invented activity, persistent browser state or hidden capture.
(() => {
  const os={home:null,knowledge:null,pulse:null,last:0,loading:false,scope:null,epoch:0,focus:false,commandIndex:0,commands:[],pulseLoading:false,pulseAt:0};
  const svgNS='http://www.w3.org/2000/svg';
  function shape(tag,attrs){const el=document.createElementNS(svgNS,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,String(v));return el;}
  const paths={presence:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 8v8 M8 12h8',ask:'M4 5h16v12H9l-5 4V5 M8 9h8 M8 13h5',knowledge:'M12 3 3 8v9l9 5 9-5V8L12 3 M3 8l9 5 9-5 M12 13v9 M12 3v10',overview:'M4 4h16v16H4V4 M4 9h16 M9 9v11',pulse:'M2 12h4l3-7 5 14 3-7h5',settings:'M5 4v16 M12 4v16 M19 4v16 M2 8h6 M9 16h6 M16 10h6',focus:'M9 3H3v6 M15 3h6v6 M3 15v6h6 M21 15v6h-6'};
  function icon(name){const el=shape('svg',{viewBox:'0 0 24 24',width:21,height:21,fill:'none',stroke:'currentColor','stroke-width':1.3,'stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'});el.append(shape('path',{d:paths[name]||paths.presence}));return el;}
  for(const b of document.querySelectorAll('.os-dock [data-view]')){const text=b.dataset.view==='ask'?'Ask':b.textContent.trim().replace(/^[^A-Za-z]+/,'');b.replaceChildren(icon(b.dataset.view),node('span','dock-label',text));b.setAttribute('aria-label',text);}
  $('focus-toggle').append(icon('focus'));
  names.presence='Home';names.pulse='Quietly, in the background.';names.ask='A place to think.';names.knowledge='Your memory, connected.';names.overview='What needs your attention.';
  descriptions.presence='';descriptions.pulse='Small, deliberate routines. You choose what runs.';
  descriptions.ask='Start with your own knowledge. Sources first; a model only when you choose.';
  descriptions.knowledge='Notes, people and projects. Follow a connection back to its source.';
  descriptions.overview='The current changes in your connected project. Nothing is sent without you.';
  const previousRender=render, previousContent=renderContent, previousOut=signedOut, previousView=selectView;
  const sections={presence:'HOME',ask:'ASK',knowledge:'MEMORY',overview:'WORK',evidence:'WORK',approvals:'WORK',activity:'WORK',sources:'CONTROLS',settings:'CONTROLS',pulse:'PULSE'};
  const viewOrder=['presence','ask','knowledge','overview','pulse','settings'];
  function reset(){os.epoch++;os.home=null;os.knowledge=null;os.pulse=null;os.scope=null;os.loading=false;os.last=0;os.pulseLoading=false;os.pulseAt=0;os.focus=false;document.body.classList.remove('os-focus');$('focus-toggle').setAttribute('aria-pressed','false');$('focus-toggle').setAttribute('aria-label','Enter focus mode');$('command-palette').close();$('command-query').value='';$('command-results').replaceChildren();}
  signedOut=function(){reset();previousOut();};
  selectView=function(view){if(!(view in sections))return;os.epoch++;os.loading=false;os.pulseLoading=false;$('detail').close();previousView(view);$('main').scrollTop=0;};
  render=function(){previousRender();if(!ui.state)return;document.body.dataset.space=ui.view;$('space-index').textContent=String(Math.max(0,viewOrder.indexOf(ui.view))+1).padStart(2,'0')+' / '+sections[ui.view];
    $('scope-name').textContent=ui.state.scope==='demo-production'?'Production workspace':pretty(ui.state.scope);
    for(const b of document.querySelectorAll('.os-dock [data-view]')){const active=sections[b.dataset.view]===sections[ui.view];if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}
    $('os-time').textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
    const tabs=$('space-tabs');const key=sections[ui.view];if(tabs.dataset.group!==key){tabs.replaceChildren();tabs.dataset.group=key;const items=key==='WORK'?[['overview','Briefing'],['evidence','Evidence'],['approvals','Decisions'],['activity','History']]:key==='CONTROLS'?[['settings','Controls'],['sources','Sources']]:[];for(const [v,label]of items){const b=button(label,'space-tab',()=>selectView(v));if(['overview','settings'].includes(v))b.dataset.subview=v;else b.dataset.view=v;tabs.append(b);}}
    for(const b of tabs.querySelectorAll('button'))b.setAttribute('aria-pressed',String((b.dataset.view||b.dataset.subview)===ui.view));
    $('focus-toggle').disabled=false;
  };
  renderContent=function(){if(os.scope!==ui.state?.scope){reset();os.scope=ui.state?.scope;}if(ui.view==='presence')home($('view-content'));else if(ui.view==='pulse')pulse($('view-content'));else previousContent();};
  function presenceFigure(count){
    const el=shape('svg',{viewBox:'0 0 400 340',class:'presence-figure','aria-hidden':'true'});
    // A quiet interface motif, not a sensor, progress meter or inference indicator.
    for(let i=0;i<22;i++){const a=i*Math.PI/22;const rx=64+Math.sin(a)*63;el.append(shape('ellipse',{cx:200,cy:165,rx,ry:122,transform:`rotate(${i*8.18} 200 165)`,fill:'none',stroke:i%4===0?'#717171':'#353535','stroke-width':.7}));}
    el.append(shape('circle',{cx:200,cy:165,r:146,fill:'none',stroke:'#202020','stroke-width':1}));
    const total=Math.min(count||0,32);for(let i=0;i<total;i++){const angle=(Math.PI*2*i/Math.max(total,1))-.4;el.append(shape('circle',{cx:200+Math.cos(angle)*146,cy:165+Math.sin(angle)*146,r:i===0?3:1.6,fill:i===0?'#dfb98b':'#858585'}));}
    return el;
  }
  function home(root){
    if(!root.querySelector('.presence')){
      root.replaceChildren();const el=node('section','presence');
      const top=node('div','presence-top');top.append(node('p','os-kicker','YOUR PERSONAL INTELLIGENCE'),node('span','home-date',new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})));
      const layout=node('div','presence-layout'),copy=node('div','presence-copy');copy.append(node('p','presence-greeting','A moment of clarity.'),node('h1','presence-title',"I’m here."));
      const sub=node('p','presence-sub','Your thoughts. Your work. A little more connected.');copy.append(sub);
      const form=node('form','presence-composer');form.id='presence-form';const label=node('label','visually-hidden','What is on your mind?');label.htmlFor='presence-query';const input=node('input');input.id='presence-query';input.placeholder='What’s on your mind?';input.autocomplete='off';input.maxLength=500;input.minLength=3;input.required=true;
      const send=node('button','presence-send','↗');send.type='submit';send.setAttribute('aria-label','Find sources for this question');form.append(label,input,send);form.addEventListener('submit',e=>{e.preventDefault();openQuestion(input.value);});copy.append(form);
      const below=node('div','presence-composer-meta');below.append(node('span','','SEARCH YOUR KNOWLEDGE'),button('Source mode','source-mode',()=>runtimeDetails()));copy.append(below);
      const picks=node('div','presence-prompts');for(const [title,q]of [['Pick up a thought','Production decisions'],['Look through my knowledge','ALFRED permissions']])picks.append(button(title+' ↗','',()=>openQuestion(q)));copy.append(picks);
      const visual=node('button','presence-memory');visual.type='button';visual.setAttribute('aria-label','Open your memory graph');visual.addEventListener('click',()=>selectView('knowledge'));const globe=node('div');globe.id='presence-globe';globe.append(presenceFigure(0));const caption=node('span','presence-caption','MEMORY / LOCAL INDEX');const n=node('span','presence-memory-count','Reading your context…');n.id='presence-memory-count';visual.append(globe,caption,n);layout.append(copy,visual);
      const strip=node('section','presence-strip');strip.id='presence-strip';strip.setAttribute('aria-label','Current context');
      el.append(top,layout,strip);root.append(el);
    }
    const s=ui.state;const send=root.querySelector('.presence-send');send.disabled=!ui.connected;
    const current=s.events.filter(e=>e.status==='current');const strip=$('presence-strip');const signature=JSON.stringify([current.map(e=>[e.seq,e.title,e.summary]),s.actions.map(a=>[a.id,a.state]),ui.connected]);
    if(strip.dataset.signature!==signature){strip.dataset.signature=signature;strip.replaceChildren();const intro=node('div','presence-strip-intro');intro.append(node('span','os-kicker','IN YOUR ORBIT'),node('p','',current.length?current.length+' current updates':'No current updates'),button('Open your work ↗','text-button',()=>selectView('overview')));strip.append(intro);for(const e of current.slice(0,2)){const b=button('','presence-update',()=>act(()=>openEvidence(e.seq)));b.append(node('span','update-kind','PROJECT UPDATE'),node('strong','',e.title),node('p','',e.summary),node('span','update-source',(e.filename||e.source)+' · '+when(e.observed_at)+'  ↗'));b.disabled=!ui.connected;strip.append(b);}if(!current.length)strip.append(node('p','presence-no-updates','Only current reports from authorised sources appear here.'));}
    if(ui.connected&&!os.loading&&Date.now()-os.last>3000){os.loading=true;const epoch=os.epoch,gen=ui.generation;api('/desk/knowledge').then(k=>{if(epoch!==os.epoch||gen!==ui.generation||ui.view!=='presence')return;os.knowledge=k;os.last=Date.now();$('presence-globe').replaceChildren(presenceFigure(k.counts.notes));$('presence-memory-count').textContent=k.counts.notes+' notes · '+k.counts.links+' references';}).catch(()=>{if(epoch===os.epoch&&$('presence-memory-count'))$('presence-memory-count').textContent='Knowledge unavailable';}).finally(()=>{if(epoch===os.epoch)os.loading=false;});}
  }
  function openQuestion(q){if(!ui.connected)return;const value=String(q).trim();if(value.length<3){showToast('Use at least three characters.');return;}selectView('ask');const field=$('ask-question');if(field){field.value=value;$('ask-form').requestSubmit();}}
  function runtimeDetails(){const body=setDialog('LOCAL NODE / CAPABILITIES');const h=node('h2','dialog-title','Present, not pretending.');h.id='detail-title';body.append(h,node('p','detail-summary','This build reads your configured local files, follows their references and creates only the local drafts you approve.'));
    const table=node('div','runtime-lines');for(const [a,b]of [['Memory & source search','Available'],['Source scanning',ui.state?.paused?'Paused':'While the local process runs'],['Voice / microphone','Off'],['External account actions','Not connected'],['Security devices','Not connected']]){const row=node('div','list-row');row.append(node('span','',a),node('strong','',b));table.append(row);}body.append(table,node('p','accessible-note','The home motif is an interface mark, not a live inference or sensor display. Sample workspace. Local data is not application-encrypted.'));
    const line=node('p','status-line','Checking local model configuration…');body.append(line);const gen=ui.generation;api('/desk/ask/status').then(s=>{if(gen===ui.generation&&line.isConnected)line.textContent=s.local_model_configured?'Configured model: '+s.model+'. Model calls require an explicit selection in Ask.':'Model not configured. Ask returns source passages, not generated answers.';}).catch(()=>{if(line.isConnected)line.textContent='Model status unavailable.';});}
  function pulse(root){
    if(!root.querySelector('.pulse-shell')){root.replaceChildren();const shell=node('section','pulse-shell');const lead=node('div','pulse-lead');lead.append(node('div','pulse-word','PULSE'),node('div','', 'The work that keeps your context in order.'));shell.append(lead);const list=node('div');list.id='routine-list';const history=node('div');history.id='routine-history';const status=node('p','status-line','Reading routine status…');status.id='pulse-status';shell.append(list,history,status);root.append(shell);os.pulseAt=0;}
    if(!ui.connected){$('pulse-status').textContent='Disconnected. Controls are unavailable.';root.querySelectorAll('button').forEach(b=>b.disabled=true);return;}
    if(!os.pulseLoading&&Date.now()-os.pulseAt>1500)loadPulse();
  }
  async function loadPulse(){const epoch=os.epoch,gen=ui.generation;os.pulseLoading=true;try{const data=await api('/desk/pulse');if(epoch!==os.epoch||gen!==ui.generation||ui.view!=='pulse')return;os.pulse=data;os.pulseAt=Date.now();drawPulse(data);}catch(e){if(epoch===os.epoch&&$('pulse-status'))$('pulse-status').textContent=errorText(e);}finally{if(epoch===os.epoch)os.pulseLoading=false;}}
  function drawPulse(data){const list=$('routine-list'),history=$('routine-history');if(!list)return;const focus=document.activeElement?.dataset.focusKey;list.replaceChildren();history.replaceChildren();
    if(!data.configured){list.append(empty('No routines on this node','This workspace is not hosted by the current process.'));return;}
    for(const r of data.routines){const row=node('article','routine-row');const index=node('span','routine-index',r.id==='memory-health'?'01':'02');const copy=node('div','routine-copy');copy.append(node('h2','',r.name),node('p','',r.description),node('small','',!r.authority_available?'Host authority unavailable':r.enabled?'Every '+intervalLabel(r.interval_seconds)+' · next '+when(r.next_due):'On demand · schedule off'));const controls=node('div','routine-controls');const toggle=button(r.enabled?'Turn schedule off':'Enable schedule','outline',()=>act(async()=>{toggle.disabled=true;await api('/desk/pulse/'+r.id+'/configure',{enabled:!r.enabled,interval_seconds:r.interval_seconds});await loadPulse();}));toggle.dataset.focusKey='schedule-'+r.id;toggle.disabled=ui.state.role!=='owner'||!ui.connected||Boolean(window.ALFRED_PREVIEW);
      const run=button('Run now ↗','primary',()=>act(async()=>{run.disabled=true;try{await api('/desk/pulse/'+r.id+'/run',{request_id:'os-'+crypto.randomUUID()});await loadPulse();}finally{if(run.isConnected)run.disabled=!ui.connected||data.paused;}}));run.dataset.focusKey='run-'+r.id;run.disabled=data.paused||ui.state.role!=='owner'||!ui.connected||Boolean(window.ALFRED_PREVIEW);if(r.last_error)copy.append(node('small','error','Last attempt: '+pretty(r.last_error)));controls.append(toggle,run);row.append(index,copy,controls);list.append(row);}
    history.append(node('div','section-top','RECENT RUNS / HISTORICAL RECORDS'));if(!data.runs.length)history.append(node('p','routine-empty','Nothing has run yet. Both schedules start off.'));
    for(const r of data.runs.slice(0,8)){const row=node('div','routine-run');const name=data.routines.find(x=>x.id===r.routine)?.name||r.routine;row.append(node('span','run-mark',r.status==='completed'?'✓':'·'),node('strong','',name),node('span','',pretty(r.status)),node('time','',when(r.started)));if(r.summary){const details=node('details');details.append(node('summary','','Inspect run'));details.append(node('pre','knowledge-source',JSON.stringify(r.summary,null,2)));row.append(details);}history.append(row);}
    $('pulse-status').textContent=(data.paused?'Processing is paused. ':'')+'Local, rule-based reports only. Schedules run while the host process is alive. No model calls or external messages.';
    if(focus){const b=Array.from(list.querySelectorAll('button')).find(b=>b.dataset.focusKey===focus);b?.focus({preventScroll:true});}
  }
  function intervalLabel(n){return n>=3600?n/3600+'h':n/60+'m';}
  $('runtime-status').addEventListener('click',runtimeDetails);$('space-back').addEventListener('click',()=>selectView('presence'));
  $('space-select').addEventListener('click',()=>{const body=setDialog('WORKSPACE');const h=node('h2','dialog-title','One space. Explicit boundaries.');h.id='detail-title';body.append(h,node('p','detail-summary',pretty(ui.state.scope)),node('p','accessible-note','Your current role is '+ui.state.role+'. Other personal or team spaces require their own authorised key. This display does not grant access to other workspaces.'),button('Sign out / switch workspace','outline',logout));});
  $('focus-toggle').addEventListener('click',()=>{os.focus=!os.focus;document.body.classList.toggle('os-focus',os.focus);$('focus-toggle').setAttribute('aria-pressed',String(os.focus));$('focus-toggle').setAttribute('aria-label',os.focus?'Leave focus mode':'Enter focus mode');showToast(os.focus?'Focus view. Source scanning and permissions are unchanged.':'Full workspace restored.');});
  const palette=$('command-palette'),input=$('command-query');
  function openPalette(){if(!ui.csrf)return;input.value='';os.commandIndex=0;commands();palette.showModal();input.focus();}
  function commands(){const q=input.value.trim().toLowerCase();const items=[['presence','Home','Your starting point'],['ask','Ask Alfred','Find the source of a thought'],['knowledge','Memory','Notes and explicit connections'],['overview','Work','Current project briefing'],['approvals','Decisions','Review exact draft proposals'],['pulse','Pulse','Bounded local routines'],['sources','Sources','Connection and scan health'],['settings','Controls','Pause, privacy and workspace access']];os.commands=items.filter(([v,t,d])=>(t+' '+d).toLowerCase().includes(q)).map(([v,t,d])=>({title:t,detail:d,run:()=>selectView(v)}));if(q.length>=3)os.commands.push({title:'Find sources for “'+input.value.trim()+'”',detail:'Search your authorised knowledge. No action will be executed.',run:()=>openQuestion(input.value.trim())});os.commandIndex=Math.min(os.commandIndex,Math.max(0,os.commands.length-1));paintCommands();}
  function paintCommands(){const results=$('command-results');results.replaceChildren();os.commands.forEach((c,i)=>{const b=button('','command-option',()=>runCommand(i));b.id='cmd-'+i;b.setAttribute('role','option');b.setAttribute('aria-selected',String(i===os.commandIndex));b.tabIndex=-1;b.append(node('strong','',c.title),node('span','',c.detail),node('small','','↵'));results.append(b);});if(!os.commands.length)results.append(node('p','command-empty','No matching space. Type a question to search your notes.'));input.setAttribute('aria-activedescendant',os.commands.length?'cmd-'+os.commandIndex:'');}
  function runCommand(i){const command=os.commands[i];if(!command)return;palette.close();command.run();}
  $('launcher-open').addEventListener('click',openPalette);$('command-close').addEventListener('click',()=>palette.close());input.addEventListener('input',()=>{os.commandIndex=0;commands();});input.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();os.commandIndex=(os.commandIndex+(e.key==='ArrowDown'?1:-1)+os.commands.length)%Math.max(os.commands.length,1);paintCommands();}else if(e.key==='Enter'){e.preventDefault();runCommand(os.commandIndex);}});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();palette.open?palette.close():openPalette();}});
  // Existing brand handler now returns to the personal home rather than a dashboard.
  document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();selectView('presence');});
  if(ui.state)render();
})();
